### ISSUE TITLE
Bottom loading bar sometimes picked up as last visual change for Chrome

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/wptagent#104]
Hi Pat,
when testing https://en.wikipedia.org/wiki/Barack_Obama we sometimes pickup a late last visual change:
<img width="1242" alt="screen shot 2018-04-23 at 10 49 17 pm" src="https://user-images.githubusercontent.com/540757/39152417-9cc672c4-4748-11e8-9799-4be755dc1fea.png">

When I look at the screenshots it looks like the bottom bar is picked up for the ones with a late last change:
http://wpt.wmftest.org/video/compare.php?tests=180423_PV_T8%2C180423_G1_S5%2C180423_ZS_QQ%2C180423_AA_P9&thumbSize=200&ival=100&end=all

We run with the default configured view port.

Best
Peter

**Comment by soulgalore** [comment]
We also have the same when we run on emulated mobile, in the last screenshots you could see the text at the bottom bar (or what's it called) signals last visual change:
http://wpt.wmftest.org/video/compare.php?tests=180426_D9_99-r%3A2-c%3A0&thumbSize=200&ival=100&end=all

We use the default view port.
Best
Peter

**Comment by pmeenan** [comment]
Sorry, was out of town for a few days.  Sounds like the size of the loading indicator may have changed and it is no longer being ignored.  I'll see if I can reproduce it and get the raw video of it happening so I can tweak the processing in visualmetrics.

**Comment by soulgalore** [comment]
No worries. I think one of the problems is that the _loading indicator_ isn't always showing everything right? so for some runs we don't see it (or finish early) and for some it's there (even though the waterfall seems to match), so you need to hit a run where it is actually showed longer than all other changes in the page.

**Comment by pmeenan** [comment]
Yep, that [looks like it fixed it](https://www.webpagetest.org/graph_page_data.php?tests=180430_J1_3a65bec6067afaf1ea64a372edc8e070&medianMetric=SpeedIndex#visualComplete) (would previously see some tests at 5+ seconds).  Let me know if you see it come back.

**Comment by pmeenan** [comment]
Increased the margin a bit more which worked locally.  Let me know if you see it again (after an hour from now or so).

On an unrelated note, there's a good chance your mobile tests aren't traffic-shaped the way you'd want them to be.  The bandwidth is specified as Kbps (not bps) so it looks like you are running a 32Mbps connection with 1300ms RTT (I assume you wanted 32Kbps since that's quite a bit of latency).

**Comment by soulgalore** [comment]
@pmeenan aha, thanks let me look into that.

Desktop works now, mobile still have the issue, check the last screenshots:
http://wpt.wmftest.org/video/compare.php?tests=180503_JP_6K-r%3A1-c%3A0&thumbSize=200&ival=100&end=all

**Comment by pmeenan** [comment]
I'm having a hell of a hard time trying to reproduce it (even with mobile emulation, the same bandwidth settings and from EC2).  Any chance you can run some tests with keepvideo=1 as an option to keep the unprocessed video?  Then I'll be able to debug the processing with a failcase video.
