### ISSUE TITLE
Certificate revocation status requests showing for Firefox

### ISSUE THREAD

**Issue by wildlyinaccurate** [WPO-Foundation/wptagent#107]
For pages loaded in Firefox, the waterfall shows certificate revocation requests. The requests vary, presumably depending on the certificate issuer(s). Example tests:

- https://www.webpagetest.org/result/180427_V2_0bf5f318a237a3619adba133c0ca84bf/1/details/#waterfall_view_step1
- https://www.webpagetest.org/result/180427_0F_7656be776318930e34853dba46943c4a/1/details/#waterfall_view_step1

Happy to try and fix this if you can point me in the right direction?

**Comment by wildlyinaccurate** [comment]
Trawling through my about:config I see two relevant configs: `security.OCSP.enabled` and `security.OCSP.GET.enabled`. Would we actually want to prevent the requests from being made, though? Or just filter them out of the timeline?

**Comment by pmeenan** [comment]
That is actually working as intended.  Firefox does OCSP validation for all certs (Chrome only does it for EV certs).  Sites can avoid the check for the leaf certificates by using stapling.

**Comment by wildlyinaccurate** [comment]
Thanks!
