### ISSUE TITLE
WPTAgent - iOS devices - inconsistent "bytes in" for objects with GZIP

### ISSUE THREAD

**Issue by timdaish** [WPO-Foundation/wptagent#114]
Using the WPTAgent (version as of 1wk ago) and WPT 17.12, I have two Apple iOS11 devices running in a private instance and the bytes-in (downloaded) size is correct for some objects served with GZIP and wrong (=uncompressed size) for other objects also served with GZIP.

The issue is repeatable over multiple tests and the different iOS devices and always seems to affect the same objects in each run. Several objects in each run report the incorrect bytes-in size.

The issue has also been replicated on public WPT using iPhone6 at: https://www.webpagetest.org/result/180503_BC_68f059dfa4526a36d47a91e514dcf053/1/details/#waterfall_view_step1 

e.g. for two objects from the same domain and each with a Content-Encoding: gzip response header:
object #12 is shown correctly with bytes-in < uncompressed size 
object #15 is shown incorrectly with bytes-in = uncompressed size.

![ios_gzip_bytes_wrong](https://user-images.githubusercontent.com/5022331/39584054-642c742e-4ee9-11e8-80ae-d620e5bfa730.JPG)

Same site tested on desktop, Android via WPT, emulation in Google Chrome and HTTPWatch on an Apple device all show the content is correctly compressed.

**Comment by timdaish** [comment]
The incorrect size is shown when there is no "Content-Length" header. The presence of the "Transfer-Encoding" header seems to [correctly] cause that. In the example site, those objects that show correct sizes have "Content-Length" headers and those that are wrong do not. 

This behavior seems to be consistent with the WPTAgent code: "safari_ios.py" lines 1144 to 1154 show that the "Content-Length" header is used if present that overrides the [wrong] encoding length...

                    # If a content-length header is available, use that instead of the values
                    # reported by Safari which only show the unencoded size (even though it
                    # claims otherwise).
                    try:
                        value = self.get_header_value(r['response_headers'], 'Content-Length')
                        if value:
                            content_length = int(value)
                            if content_length >= 0:
                                request['objectSize'] = content_length
                                request['bytesIn'] = content_length + \
                                        sum(len(s) for s in request['headers']['response'])

A similar issue was previously reported for WebKit Safari Web Inspector - https://bugs.webkit.org/show_bug.cgi?id=170597 in 2017 and various posts indicate Safari has had this issue for several years.

I'm looking at an HTTPWatch-generated iOS HAR file and HTTPWatch Studio manages to calculate and display the compressed size despite the missing Content-Length header. 

With its Content-Encoding defined as GZIP, this object passes the GZIP checks with a score of 100. If the "_gzip_save" was also calculated also when the Content-Length header was found to be missing, then it could be used to calculate a valid content-length for the object (albeit with a defined compression level that may or may not match the original). Can you please consider if that would be an acceptable workaround to this issue. I'll also check with andydavies for a view on this approach.

regards,
Tim

**Comment by pmeenan** [comment]
Fix is rolling out to the public devices now (will be complete within the next hour).  Here is the iPhone 6 with the fix: https://www.webpagetest.org/result/180507_AY_314e708cddeee32395a70fb0f2a47712/

![image](https://user-images.githubusercontent.com/444165/39720150-617c00f0-5209-11e8-8b84-ba7cd66fecf6.png)

On an unrelated note, if you are running private iOS devices with 11.3 you should enable "Javascript" in addition to "Inspector" in the Safari Advanced settings.  That will re-enable the javascript timings when timeline capture is enabled (going to update the docs shortly).

**Comment by timdaish** [comment]
many thanks for the update.
