### ISSUE TITLE
Filmstrip is botched after form submission using a script

### ISSUE THREAD

**Issue by sergeychernyshev** [WPO-Foundation/wptagent#117]
Filmstrip screenshots get botched when submitting a form using a script: http://www.webpagetest.org/video/compare.php?tests=180504_KA_d49a3fb2c866b558440c780602fbcd82-r:1-c:0

Reproduced with script as small as this:
```
logData 0
navigate	https://secure.meetup.com/login/

setValue	name=email	some@email
setValue	name=password	somepassword
click	name=submitButton

logData	1
navigate	https://www.meetup.com/Web-Performance-NY/
```

This is how filmstrip looks like after this test runs
![screen shot 2018-05-04 at 5 36 31 pm](https://user-images.githubusercontent.com/38076/39654686-e629566a-4fc3-11e8-803a-48e5695d579a.png)

Individual screenshot image itself:
![ms_003000](https://user-images.githubusercontent.com/38076/39654690-ec9165ba-4fc3-11e8-98c3-458f770fbe3a.jpg)

Final screenshot looks OK though:
![1_screen](https://user-images.githubusercontent.com/38076/39654731-1a2dd15c-4fc4-11e8-9f25-355cfa1020e8.jpg)

**Comment by sergeychernyshev** [comment]
OK, it looks like this only happens when you use "click" followed by navigation (I assume it is a mistake to do that).

Replacing "click" with "clickAndWait" solved the problem.

Please close this if it was just a rookie mistake with "...AndWait".

**Comment by wildlyinaccurate** [comment]
@pmeenan I just stumbled across this exact issue (and resolution) today. Do you know why the "AndWait" commands do this? From what I can see in the code, the "AndWait" part is just ignored and it's no different to a regular command..?

**Comment by pmeenan** [comment]
andWait starts a measurement where the agent waits for the navigation or network activity to complete. Like measuring a login. Without the andWait it goes right on to the next script step immediately.

________________________________
