### ISSUE TITLE
Test fails with "browser crashed" if service worker crashes

### ISSUE THREAD

**Issue by wildlyinaccurate** [WPO-Foundation/wptagent#118]
This is a weird issue that I can't replicate locally, but it looks like the service worker for [this test](https://www.webpagetest.org/result/180506_ST_37aba68ee060535895c68ff04d6cc0f8/) is crashing, and wptagent is receiving the `Inspector.targetCrashed` message and taking that to mean the main frame crashed.

I assume that this is not the expected behaviour? If that's the case, would you be happy for me to submit a patch that records the main frame ID and only reports an error when a "bad" event comes from the main frame?

**Comment by pmeenan** [comment]
Wow, bizarre - I've never seen that.  Must be new to service workers that the sw process can crash but not take down the whole session.  Unually an inspector crash takes out everything.

It's not so much a "frame" as it is a worker session.  I'll see about adding logic to ignore crash events for anything but the main session.

**Comment by pmeenan** [comment]
Verified the [fix works](https://www.webpagetest.org/result/180506_QC_cdc04d312ff588ef553dbf24621ecdc4/) (could reproduce the crash happening before).  It is rolling out now.  You folks find the best issues :-)

I will say, I feel a little bad not letting the site know that their service worker is doing something to cause the Chrome worker process to crash.  I can't really think of a good way to expose it though.

**Comment by wildlyinaccurate** [comment]
Ha - the best issues for the best browser automation platform!

Yeah, that part was tripping me up a little bit as well. I couldn't think of anything short of adding a new field to the result object... `noteworthy_events :: [Event]` <sup><small>(joking but also kinda not)</small></sup>
