### ISSUE TITLE
iOS support for basic authentication

### ISSUE THREAD

**Issue by j0weiss** [WPO-Foundation/wptagent#129]
While trying to test a page which is protected by basic auth I saw that this is currently not supported by the [iWptBrowser](https://github.com/WPO-Foundation/wptagent/blob/master/internal/safari_ios.py).
Is it just a matter of adding functionality in the agent or is there also work to be done in the [iWptBrowser App](https://github.com/WPO-Foundation/iWptBrowser)?

**Comment by pmeenan** [comment]
Modifying headers (required for basic auth) and setting cookies isn't currently possible.  Setting cookies may be doable on iOS 11 with modifications to iWptBrowser (was planning on looking at it).

It looks like webkit supports [Network.setExtraHTTPHeaders](https://trac.webkit.org/browser/webkit/trunk/Source/JavaScriptCore/inspector/protocol/Network.json#L159) on the remote debug protocol so it may be trivial to add to safari_ios.py.  I don't have my iOS dev environment handy right now but I can take a crack at implementing it tomorrow.

**Comment by pmeenan** [comment]
Took a blind stab at implementing it and it appears to work.  Should be live on the public iOS agents within the next hour.  Let me know if it works for your test case (if not there is another issue I'll have to fix).

**Comment by j0weiss** [comment]
Awesome, it works just fine!
Thanks a lot for the quick fix.
