### ISSUE TITLE
tc: command not found

### ISSUE THREAD

**Issue by soulcorrosion** [WPO-Foundation/wptagent#136]
When I start the docker agent with the following commands:

sudo modprobe ifb numifbs=1
sudo docker run  -p 4001:80 --network="host" -e SERVER_URL="http://localhost:4000/work/" -e LOCATION="Test" -e EXTRA_ARGS="--shaper netem,eth0" --cap-add=NET_ADMIN webpagetest/agent

Inside the container I get the following errors: 

sudo: ip: command not found
sudo: ip: command not found
sudo: tc: command not found
sudo: tc: command not found
sudo: tc: command not found

I entered the container and confirmed that executing the tc command does not work. 
What am I missing here? I have the feeling I'm missing a small detail. 
@sburnicki can you also have a look?

Thank you very much.

**Comment by fbuecklers** [comment]
It seems that the latest wpt docker image isn't build correctly. 
If you install iproute2 and libnss3-tools afterwards in the docker container the container works again.
`docker exec containerId apt-get install -y libnss3-tools iproute2`

**Comment by soulcorrosion** [comment]
@fbuecklers thank you very much. You made my day.
@pmeenan also noticed your commit. :)

Thanks guys. Closing

**Comment by oliverdevisser** [comment]
Nice
