### ISSUE TITLE
Windows EC2 agents VS Linux EC2 agents

### ISSUE THREAD

**Issue by rposbo** [WPO-Foundation/wptagent#137]
Looks like Windows Chrome agents don't collect the same data as the Linux EC2 Agents:

![wpt wtf](https://user-images.githubusercontent.com/316233/41601823-4e1c91b6-73d1-11e8-8bc2-cac078f8274c.PNG)

Same URL, same location, Private EC2 WPT instance with EC2 agent auto scaling, EU vs EU-linux agents.

**Comment by pmeenan** [comment]
Should be [fixed now](https://github.com/WPO-Foundation/webpagetest/commit/26e3cf061c2395c949e125a155647db08eaf18b5) (within the next hour for already-running instances).
