### ISSUE TITLE
Block URL for lighthouse

### ISSUE THREAD

**Issue by sandeepsingh3** [WPO-Foundation/wptagent#144]
Can we please enable --blocked-url-patterns for lighthouse. At the moment we are passing blocked URLs from WPT however it is not reaching lighthouse 

is there a way to pass these to lighthouse 

https://github.com/WPO-Foundation/wptagent/pull/33/commits/04ad1b76efab12f68f4442dfcbc03f07ab8d389e

**Comment by pmeenan** [comment]
Looking into it.  Right now lighthouse is throwing an error whenever more than one pattern is passed so I pinged the lighthouse team to have them take a look.
