### ISSUE TITLE
Firefox not working on Windows agents

### ISSUE THREAD

**Issue by bbraz** [WPO-Foundation/wptagent#145]
It appears that trying to run a test using Firefox on a Windows platform is currently not working:

https://www.webpagetest.org/result/180704_JD_75e9e73db02b4e4b612b5f9c62f45e6d/

We get the following error when trying to run a job using Firefox.

First View: Test Error: Error starting Firefox: setWindowPosition stacktrace: WebDriverError@chrome://marionette/content/error.js:178:5 UnknownCommandError@chrome://marionette/content/error.js:472:5 despatch@chrome://marionette/content/server.js:287:13 execute@chrome://marionette/content/server.js:268:11 onPacket/<@chrome://marionette/content/server.js:243:15 onPacket@chrome://marionette/content/server.js:242:8 _onJSONObjectReady/<@chrome://marionette/content/transport.js:500:9

**Comment by pmeenan** [comment]
Should be [fixed](https://www.webpagetest.org/result/180704_9G_00d9fcb7aab70778ad28520f549e0e63/) in [this commit](https://github.com/WPO-Foundation/wptagent/commit/8c4c74c657b32c638a9ad95d9c22dbbeb51540b8) (just now).  Looks like some of the Firefox remote commands weren't implemented in their move to Rust (accidentally) but set_window_rect is working so I switched to that.

Feel free to reopen if you see the issue pop back up.
