### ISSUE TITLE
setHeader command does not respect filter option.

### ISSUE THREAD

**Issue by mmmurray** [WPO-Foundation/wptagent#155]
I have been trying to use the `setHeader` command described here:
https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting#TOC-setHeader

Adding a regex for the `filter` option seems to have no effect, the header is applied to all requests regardless of hostname.

This is the script I have tried:
```
setHeader	if-none-match: abcdefghi	www\.bbc\.co\.uk
navigate	https://www.bbc.co.uk/sport
```
(Test run: https://www.webpagetest.org/result/180712_NY_2c944a7e0ef462fe5104e7962447bd0f/)

I'm not sure if I have the syntax right because I couldn't find an example to go off.

**Comment by pmeenan** [comment]
The filtering hasn't been implemented in wptagent yet and I'm not sure it will be possible (at least for Chrome).  The [dev tools interface](https://chromedevtools.github.io/devtools-protocol/tot/Network#method-setExtraHTTPHeaders) for Chrome for adding headers applies them universally.  There are other ways to do it (request intercaption or extension) but both of those add overhead to the actual requests and would have a performance impact.

**Comment by mmmurray** [comment]
Ah, that's a shame, thanks for your help. To give more background on the specific problem I am trying to solve in case you know of something else that would work. We want to simulate a repeat visit view as though a user visited the page once per day. Because WPT runs the repeat view test immediately after the first view, some resources with a very short cache timeout are still served from the cache when in reality, they wouldn't for a real user.

Is there a way of advancing time in a test or busting the cache for particular resources?

**Comment by pmeenan** [comment]
A more likely solution would be to implement the [expireCache command](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting#TOC-expireCache) in wptagent (not yet implemented).  That will let you clear any resources from cache that have a short cache duration.

It should be possible to [walk the cache storage](https://chromedevtools.github.io/devtools-protocol/tot/CacheStorage) and delete individual entries that way.

I know it's also possible on IE but probably won't be possible for Firefox (if it matters).

**Comment by pmeenan** [comment]
:(  Maybe not (at least through the API).  That looks to be specific to the cache storage API and not all caches.  Looking to see if at least on Linux (and maybe Android) I can clear the cache entries from the filesystem directly.

**Comment by savsav** [comment]
There is also the issue of sharing your development instance credentials with all third parties when you use credentials (through the Authorization header).

**Comment by rockeynebhwani** [comment]
@savsav  - This issue is 'Closed'. Worth re-opening a new issue for @pmeenan
