### ISSUE TITLE
setUserAgent/UAModifier don't work in IE and Edge

### ISSUE THREAD

**Issue by wildlyinaccurate** [WPO-Foundation/wptagent#157]
Still don't have a Windows testbench so can't submit a patch for this one, sorry!

**Comment by pmeenan** [comment]
Edge may be possible with an extension (though I'm a bit worried about the request interception overhead).  Still looking to see if there is a reg key or webdriver way to do it.

For IE 11 it looks like the registry will work ([with some hoops](https://social.technet.microsoft.com/Forums/ie/en-US/aba740ee-aae1-4941-b684-3ef668c204ac/how-to-append-the-user-agent-string-in-ie11?forum=ieitprocurrentver)) but it puts the UA modifier in the middle of the string:

```
Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; PTST/xxx.yyy; rv:11.0) like Gecko
```

That's probably better than not having it but may mess up some implementations.  That said, it's better than not having it so I'll take a stab at it.

**Comment by pmeenan** [comment]
Should work for IE 11 now (well, within the next hour as the update rolls out).  Haven't implemented it for Edge yet until I get a sense for the overhead cost or find a better way.

**Comment by wildlyinaccurate** [comment]
Ha, that is some registry black magic right there. Classic MS. I'm happy without a fix for Edge, to be honest. SpeedCurve don't test in Edge and I (personally) don't rely on the UA modifier when I test in Edge. Thanks for the quick turnaround!
