### ISSUE TITLE
OCSP requests on Firefox aren't ignored for TTFB

### ISSUE THREAD

**Issue by sburnicki** [WPO-Foundation/wptagent#160]
When testing a page with Firefox, the OCSP request accounts for the TTFB:
http://www.webpagetest.org/result/180724_TG_377229a501858985c049f7612ffd94ea/1/details/#waterfall_view_step1

It should be ignored, so the TTFB of the real HTML requests is reported.

**Comment by stephendonner** [comment]
@sburnicki @bwollmer (and @pmeenan): should this be now (marked) fixed?

**Comment by pmeenan** [comment]
Yep, looks to be handled.
