### ISSUE TITLE
Lighthouse: pass through cookies from WPT script

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/wptagent#167]
Thanks for adding headers support to Lighthouse tests. Is it also possible to pass through any cookies set in a script through as options in --extra-headers?

**Comment by pmeenan** [comment]
Can you try it with headers for a few sites you need it to work on to see how well it works?  That might work for network-based checks but any javascript that reads cookies won't see them.

**Comment by zeman** [comment]
Here's the example I was working with which is a simple cookie to turn off pop ups. Switching to setHeader worked well in Lighthouse.

setHeader	cookie: nl_cookiewall_version=1
navigate	https://www.volkskrant.nl/

[Before](https://wpt1.speedcurve.com/lighthouse.php?test=180813_JG_4b8633bbc63714c66712216c5bedd563&run=4) & [after](https://wpt1.speedcurve.com/lighthouse.php?test=180814_ET_20a5a4609989dfacc910f4db339f60d5&run=4)

**Comment by pmeenan** [comment]
Thanks.  May be a few days before I can tackle it but looks good even if it won't handle all cases.

**Comment by abarre** [comment]
@zeman can you, please, confirm that you bypass the issue with `setCookie` by using `setHeader cookie`. Do you end up using both line in your script :
```
setCookie https://www.volkskrant.nl/ nl_cookiewall_version=1 #for chrome
setHeader	cookie: nl_cookiewall_version=1 # for lighthouse
navigate	https://www.volkskrant.nl/
```

Is it equivalent ?

@pmeenan, I see that you describe a potential solution on #202 using Network.getCookies. Did you try this solution ?

**Comment by abarre** [comment]
I see the difference now : 
```
--extra-headers "/home/ubuntu/wptagent/work/ip-10-0-0-144/180814_ET_20a5a4609989dfacc910f4db339f60d5.1.0/lighthouse-headers.json"
```
@zeman, did you patch your agent with this change ?

**Comment by zeman** [comment]
@abarre yes setHeader should work for settings cookies in LightHouse. I would just use the setHeader, no need to have setCookie as well.
