### ISSUE TITLE
WPT metrics vs Lighthouse metrics

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/wptagent#176]
We're seeing some interesting differences between the metrics reported by WPT and then the Lighthouse report that runs at the end of the test. Lighthouse says that the network and cpu throttling is provided by the environment which is WPT so we would expect the metrics to be with the same range.

In [this example](http://www.webpagetest.org/result/180828_68_87730014b09311b2e669a5867ad2cb13/) the speedindex range in WPT across the 3 runs was 6.499s - 8.889s yet Lighthouse reported a time of 21.6s which is much slower.

In the WPT UI is says that Lighthouse "(Uses a "3G Fast" connection independent of test settings)". Is that what's happening here even though Lighthouse says that the network throttling was provided by the environment?

**Comment by pmeenan** [comment]
2 possibilities. #1, yes, lighthouse always uses a 3G Fast profile independent of the test config and #2, lighthouse uses the ssim version of speed index which can be very sensitive to content movements.

________________________________

**Comment by zeman** [comment]
I reran the test using 3G Fast in WPT and the numbers are a lot more comparable so I think that's it. Thanks Pat!

WPT SpeedIndex (21.450s - 22.448s)
Lighthouse SpeedIndex (23.350s)

**Comment by pmeenan** [comment]
FWIW, the lighthouse scores are calibrated against a 3G Fast profile which is why the speed is fixed. Otherwise the scores would change based on the test settings.

________________________________

**Comment by lukaszmorawski** [comment]
Why is Lighthouse always fixed on 3G Fast? When I run test I would like to have all settings consistent. We also run tests with different settings (network,cpu,device) to see Lighthouse metrics (like FMP) on mobile/desktop. Is there any plan to change it?
