### ISSUE TITLE
Can't set cookies in Edge

### ISSUE THREAD

**Issue by PhilAlbrecht** [WPO-Foundation/wptagent#177]
Hey there,

I've been trying to setCookies for Edge, but it doesn't seem to work.

Chrome: https://www.webpagetest.org/result/180905_CW_7994e997820957cdd3502758ad05ee0f/1/details/
Firefox: https://www.webpagetest.org/result/180905_M0_749375daf34aa1d388acac98fdb8ded4/1/details/
Edge: https://www.webpagetest.org/result/180905_YG_5d6844ee81b1df2fd8a544a398226676/1/details/

Instead of `cookie: TEST-COOKIE=asdf` like firefox and chrome, Edge got:
`Cookie: OGPC=19007686-1:; 1P_JAR=2018-8-22-12; NID=126=T_w7Z--gmj2M1U1vKcgHk6yFRfSEAtQ2QAO3kB8JLG4AlfBFilLMBl8XC0HNPTiNyuXv94hccq-JofWJlj5phmoOmZkG8mh95hD8mwsHvcWQPXiIG3044n0IIYlUWIY`. Probably changes in Edge or Webdriver? Any idea for a workaround or fix?

thanks, kind regards Phil.

**Comment by PhilAlbrecht** [comment]
We investigated the issue and found out that cookies can be set from the edge extension if we include an expiration date. However this is currently not supported by the agent. Before we implement a fix, is there a security reason, or any other concern for not being able to set an expiration date?

**Comment by pmeenan** [comment]
No, no security reason, just never implemented.  The edge extension should
be able to just apply a far-future expiration since the cache is explicitly
cleared as needed.

**Comment by pmeenan** [comment]
Not wanted.  If that's the case then cookie clearing isn't working for Edge and would need to be fixed as well (and could be a larger problem).

**Comment by PhilAlbrecht** [comment]
After having a look at it, we couldn't find the folder where the edge cookies are saved. We thought about extending the extension, in order to run a script after the test to delete the cookies through the extension. Any thoughts on that? Or maybe a better idea how to handle this?

**Comment by pmeenan** [comment]
If the extension has access to all cookies (even non-JS cookies) then it might be a good path to get to them.  I thought I remembered something about Edge and IE moving to a shared OS cookie store which is when Edge moved them out of it's app data folder but I never could find it or find an OS-level API that worked for clearing them (or it keeps changing).  I think I asked the Edge team at one point but didn't get an answer that worked.

If you find a way to do it in the extension, make it controllable by a setting from the agent so it is only cleared when there is no repeat view test to run.

**Comment by PhilAlbrecht** [comment]
We were not able to find cookies set through setCookie with the extension. so we are probaply only able to remove the cookies set through javascript, which includes the cookies we are setting through the test. That would be a somewhat improvement to now. :/ edge is kinda frustating

**Comment by PhilAlbrecht** [comment]
Okay I updated the pull request for clearing the Microsoft Edge cache. I am using _winreg to set the "clear cache after closing the browser" option in Edgefor the firstview only or the repeated view step. This should do it, i guess.
