### ISSUE TITLE
timeToDOMContentFlushed custom-metric is null in Firefox Nightly, but correct UNIX Epoch time in latest release build

### ISSUE THREAD

**Issue by stephendonner** [WPO-Foundation/wptagent#186]
Steps to Reproduce:

In both steps 1 and 3, paste in the following JS snippet to the Custom tab (to the right of Advanced Settings), Custom Metrics textarea:

`[timeToDOMContentFlushed]
return window.performance.timing.timeToDOMContentFlushed;`

(With a line break between the metric variable and the ```return``` line.)

(Alternatively, add https://github.com/mozilla-services/webpagetest-settings/blob/94f53bcdb5217ff6808a977c364d7ad5ff9ff2fc/custom_metrics/domContentFlushed.js to the server/API instance.)

1. Run a test against Firefox desktop (latest release), like so: https://www.webpagetest.org/result/181004_EA_a86fb438ac6481dd1da32bd887c03da4/
2. Load https://www.webpagetest.org/result/181004_EA_a86fb438ac6481dd1da32bd887c03da4/?f=json and grep for ```timeToDOMContentFlushed```; here, it's ```1538633719103``` which converts/is a UNIX Epoch Time timestamp:
```
1538644619 seconds since Jan 01 1970. (UTC)
This epoch translates to:
10/04/2018 @ 9:16am (UTC)
```
3. Run a test against Firefox Nightly (desktop), like so: https://www.webpagetest.org/result/181004_1X_196de9502ca2b466559a72902fcafafb/
4. Load https://www.webpagetest.org/result/181004_1X_196de9502ca2b466559a72902fcafafb?f=json and grep for ```timeToDOMContentFlushed```

Actual Results:

```timeToDOMContentFlushed:    null``` appears under data | runs | median | firstView | custom

Expected Results:

Similarly appropriate/accurate UNIX Epoch Time timestamp in Nightly, as works in Firefox desktop release builds (at least on Linux)

<img width="1920" alt="screen shot 2018-10-03 at 11 45 47 pm" src="https://user-images.githubusercontent.com/387249/46465147-d4829580-c77c-11e8-9dc7-b0e5b3ac89e9.png">

**Comment by soulgalore** [comment]
@stephendonner could it be that nightly doesn't pick up the preferences (I haven't looked)? Latest on Mac 64.0a1 (2018-10-04) works.

**Comment by stephendonner** [comment]
Fixed by https://github.com/WPO-Foundation/wptagent/issues/216#issuecomment-439713162.

Here's a screenshot showing it working from https://www.webpagetest.org/result/181204_FV_346faf2e481df64c06b443391410e4bb/?f=json and https://www.webpagetest.org/result/181204_FV_346faf2e481df64c06b443391410e4bb

<img width="2032" alt="screen shot 2018-12-04 at 4 25 12 pm" src="https://user-images.githubusercontent.com/387249/49474557-ff23b580-f7e2-11e8-99fc-9d277381d161.png">
