### ISSUE TITLE
Firefox multistep: Request in wrong step

### ISSUE THREAD

**Issue by bwollmer** [WPO-Foundation/wptagent#189]
If you run a multi step script in firefox, it seems like some requests of the previous step will be in the following step. Here is an example:
https://www.webpagetest.org/result/181008_G3_d3a8c4ca14013a4a17beb2ea4dd45b57/1/details/ 
On the screenshot below or step PL:::OTTO_Produktliste_geschirrspueler the first request should't be there. If you inspect the request, you see a negative start time, so I assume that the request belongs to the previous step. The same for the next 2 requests.
![negative_start](https://user-images.githubusercontent.com/12231522/46603824-8e1e9500-caf4-11e8-9954-79e69ba69e3c.png)

I tried to debug this behavior, but I'm kind of stuck and would appreciate some help. 
In firefox.py:415 the negative time is calculated, because the task start time is greater than the event time.
But I don't know why the message even arrived in this method. Sure, we got it from the message server, but if the problem would be in the message server, this behavior should also appear in other browsers. So I would assume that the problem has to be in firefox.py.
Do you have any idea, where I could look further or why this message arrived in _process_message_?

**Comment by bwollmer** [comment]
Thanks for your feedback! The log seems fine, there is already a line to filter old data out.
We found out that the extensions still reports data, while the current data is processed. In that case the message will be in the queue of the message server, until the next steps starts, which then polls the queue and will receive the old data.
Edge already implemented the logic to empty the queue before each step, I tried to apply the same logic to firefox. This reduced the problem to fewer messages from old steps, but this is just "luck" because firefox still runs in the background and we just minimized the time frame for the concurrent push to the queue.
To get a deterministic result I implemented a filter in firefox.py:process_messages, to filter messages with a negative timestamp. While this solved the problem of old requests in steps, we saw that there is another problem, with and without this fix.

On the first screenshot I posted, you can see that 3 css requests are before the 7. requests. But the 7. requests is the main request and the referrer of the css files, so it"s not possible that the 3 requests happened before that one. We could track this issue down to the merging of log and extension data, but at this point we haven't figured out the exact problem. Below are two screenshots. In both my fix with the old requests is not implemented.  In the first one I disabled all log data and in the second all extension data. In both cases the order seems right. But if both are merged, the order is wrong, like in the first screenshot.

Could you give us some insight, why we have extension and log data and why they are merged like this? The code reads like the log always tells the truth and will overwrite extension data, so do we assume that the extension data is 'wrong'?

I haven't opened a merge request for the fist problem yet, because the problems seems kind of related, so I would try to fix both of them in one, if  that's ok for you. 
Thanks for your time!
![waterfall_extenion_only](https://user-images.githubusercontent.com/12231522/46663393-4a905d80-cbbe-11e8-9165-b96ea28df30f.png)
![waterfall_log_only](https://user-images.githubusercontent.com/12231522/46663397-4cf2b780-cbbe-11e8-85b8-08798e9c8efc.png)

**Comment by pmeenan** [comment]
The log data is the ultimate source of truth since it is recorded by the networking stack and has much more accurate timings.  The extension data is mostly for backfill in case the log couldn't be parsed or some requests were missing for some reason.  The same thing is done for Chrome with the dev tools events and the netlog trace events.

The extension data in both Chrome and Firefox tends to be less-right (not necessarily wrong) than the logs which is why it is used as a fallback.

There is probably something with the alignment of the timestamps between the extension and the logs that causes them to re-order when merged and some requests aren't available.  It might be worth trying to figure out why most of the js and css in the logs-only version are showing as -1.  If the requests were actually sent then it's a sign that the responses weren't parsed.

**Comment by bwollmer** [comment]
It seems like adjust_timings was the problem. The method was only called for the first step. I altered the code to run this for every step, since I could't find a reason that this should only apply to the first step. This fixed the wrong order of requests and the first request of every step now starts at 0 again, like with the other browsers. (see https://github.com/WPO-Foundation/wptagent/pull/201)
