### ISSUE TITLE
Testing with Firefox is broken

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/wptagent#204]
I saw this on our internal WebPageTest, and it's the same on WebPageTest.org.
<img width="1552" alt="screenshot 2018-10-25 at 14 35 34" src="https://user-images.githubusercontent.com/540757/47500612-8afd0600-d863-11e8-8d85-633f019d46ef.png">

See https://www.webpagetest.org/result/181025_74_ef7dd06ac8ff2540af9b7f3a0ac78bec/

**Comment by pmeenan** [comment]
Current thought is outdated marionette pip modules.  I just pushed an agent update that auto-updates outdated pip modules and am waiting for it to get picked up to see if that fixed the issue.  Updating the modules from within python may not work well though (for the current process anyway) so I may have to re-think it.

**Comment by pmeenan** [comment]
Took a few attempts but it looks like the agent is now successfully updating all of the pip modules at startup and Firefox should be working: https://www.webpagetest.org/result/181025_DG_14ee8c7c4c637205ff34e98bd797b04b/

**Comment by soulgalore** [comment]
Great, it works now, thank you!
