### ISSUE TITLE
lstat .git: no such file or directory

### ISSUE THREAD

**Issue by joacim-boive** [WPO-Foundation/wptagent#21]
Trying to do a docker build of the latest dockerfile and I am getting the below:

You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
 ---> 96276f9afba8
Removing intermediate container 3fc8c7a5d7c3
**Step 7/13 : COPY .git /wptagent/.git**
**lstat .git: no such file or directory**

What can I do about that?

**Comment by sburnicki** [comment]
The current docker image is written to do auto-updates via git, thus requires the whole cloned git repository.
So you either need to clone the whole repo, or delete this line from the Dockerfile and disable auto-update when running the container. See [docs/docker.md](docs/docker.md)
