### ISSUE TITLE
Windows agents get stuck on RDP certificate dialog

### ISSUE THREAD

**Issue by wildlyinaccurate** [WPO-Foundation/wptagent#213]
We had been running a modified Windows AMI and ran into this problem the other day. We switched to the [public AMIs](https://github.com/WPO-Foundation/webpagetest-docs/blob/master/user/Private%20Instances/ec2_agents.md#ami-images) and that seemed to solve the issue, but only for about 2 days. Now all of the agents get stuck on the same dialog:

![screenshot from 2018-11-13 03-59-36](https://user-images.githubusercontent.com/794263/48361659-d4c06a00-e706-11e8-9731-b623a49b18c4.png)

For now we've just created a new image with the certificate already installed. Is there a better way to resolve it?

**Comment by pmeenan** [comment]
Oh joy.  I'll update the base images and see if that helps.  I wonder if it might also be an out of date root certificate file or something.  The agents auto-update the certs but that won't help if RDP itself refuses to start.

**Comment by pmeenan** [comment]
Looks like I may be able to disable the RDP cert check in the registry: https://serverfault.com/questions/591154/remote-desktop-certificate-error-how-to-connect-anyways

**Comment by rdejuana** [comment]
I don't mean to nag, but do you have a status on this issue?

**Comment by pmeenan** [comment]
I probably won't get a chance to update the images until tomorrow. If you need it before then you'll have to copy the Ami and update your copy of it.


________________________________

**Comment by pmeenan** [comment]
Windows AMI's have [all been updated](https://github.com/WPO-Foundation/webpagetest-docs/commit/db5da4766ffe3b79c7371910d707d99b404a63ed) to ignore certificates for the RDP connections as well as with all of the latest Window updated.
