### ISSUE TITLE
Use latest release of Lighthouse

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/wptagent#215]
It looks like WPT agents update their version of Lighthouse from the master branch. Could we switch instead to the latest release?

At the moment agents are using Lighthouse version v4.0.0-alpha.1 rather than the latest release which is v3.2.1.

**Comment by pmeenan** [comment]
It should use the latest published to npm's main tree. "next" or something like that is the unstable release.


________________________________

**Comment by pmeenan** [comment]
Looks like the alpha was published to the main release 21 hours ago: https://www.npmjs.com/package/lighthouse

If they published it by accident you should open an issue on the lighthouse repository.


________________________________

**Comment by zeman** [comment]
Thanks Pat, just saw that. I'll ping Lighthouse instead.
