### ISSUE TITLE
Seeing many First View: Test Error: Unhandled exception in test run: '7798:1' type of errors. EC2 Linux AMI Running 181115.161114 version wptagent

### ISSUE THREAD

**Issue by padibona** [WPO-Foundation/wptagent#217]
Hello,

Starting at around 11/15/2018 at 10:25 AM Central Time I started seeing several tests that fail with an error similar to First View: Test Error: Unhandled exception in test run: '7798:1'

An example is here: https://www.webpagetest.org/results.php?test=181116_1N_af81bdfacb680526f23c1fff676841a3 

That example was pushed from our private EC2 to the Public.

We are running the following AMIs and wptagent versions:
wpt-linux-20180404 (ami-a88c20d5) - 181115.161114
wpt-linux-20180404 (ami-1771676b) - 181115.161114
wpt-linux-20180404 (ami-dceab537) - 181115.161114

We run only Chrome.

Interestingly some URLs seem to cause the errors more frequently:

http://www.target.com/
http://www.fender.com/
http://store.snapon.com/
http://www.joovy.com/

Is there a way to debug things on the agents?

Any ideas?

Thanks,

Pete

**Comment by padibona** [comment]
00:40:09.506 - python /home/ubuntu/wptagent/internal/support/visualmetrics.py -i /home/ubuntu/wptagent/work/ip-/181117_TJ_50.1.0/1_video.mp4 -d /home/ubuntu/wptagent/work/ip-/181117_TJ_50.1.0/video_1 --force --quality 100 --viewport --orange --maxframes 50 --histogram /home/ubuntu/wptagent/work/ip-/181117_TJ_50.1.0/1.0.histograms.json.gz --progress /home/ubuntu/wptagent/work/ip-/181117_TJ_50.1.0/1_visual_progress.json.gz -vvvv --forceblank
00:40:09.517 - Resetting traffic shaping
00:40:09.607 - Processed 284 trace events
00:40:09.623 - Collecting trace events
00:40:10.604 - Processed 27722 trace events
00:40:10.795 - Processed 8947 trace events
00:40:10.839 - Post-Processing the trace netlog events
00:40:10.843 - Processing the trace timeline events
00:40:10.905 - Unhandled exception in test run: '14816:1'
Traceback (most recent call last):
  File "wptagent.py", line 180, in run_single_test
    browser.run_task(self.task)
  File "/home/ubuntu/wptagent/internal/chrome_desktop.py", line 127, in run_task
    DevtoolsBrowser.run_task(self, task)
  File "/home/ubuntu/wptagent/internal/devtools_browser.py", line 222, in run_task
    self.on_stop_recording(task)
  File "/home/ubuntu/wptagent/internal/chrome_desktop.py", line 194, in on_stop_recording
    DevtoolsBrowser.on_stop_recording(self, task)
  File "/home/ubuntu/wptagent/internal/devtools_browser.py", line 187, in on_stop_recording
    self.devtools.collect_trace()
  File "/home/ubuntu/wptagent/internal/devtools.py", line 449, in collect_trace
    self.websocket.stop_processing_trace()
  File "/home/ubuntu/wptagent/internal/devtools.py", line 1184, in stop_processing_trace
    self.trace_parser.ProcessTimelineEvents()
  File "/home/ubuntu/wptagent/internal/support/trace_parser.py", line 444, in ProcessTimelineEvents
    for name in self.cpu['slices'][thread].keys():
KeyError: '14816:1'
00:40:10.945 - DevTools websocket disconnected
00:40:10.947 - Starting new HTTP connection (1): localhost:9265
00:40:10.948 - http://localhost:9265 "GET /json/close/B163FE576135CF6FB7B6A8622D8E426A HTTP/1.1" 200 17
00:40:10.967 - Stopping browser
00:40:10.967 - Terminating all instances of chrome
00:40:11.024 - Waiting up to 30 seconds for chrome to exit
00:40:11.154 - Test run time: 22.370 sec
00:40:11.155 - Uploading result

Chrome 70 fallout?

**Comment by pmeenan** [comment]
I think I know what is causing it (related to the identifying of main thread activity in 70). Just pushed a fix (I think). The agents should pick it up within the next hour (or you can force it by rebooting them).

**Comment by padibona** [comment]
Looks good! Thanks for the super quick turn around time.
