### ISSUE TITLE
Auto-updating docker container is not stable

### ISSUE THREAD

**Issue by sburnicki** [WPO-Foundation/wptagent#22]
As I feared, the auto-updating container is pretty fragile.
For example, our agents stopped working at some point, because the npm update command resulted in errors like:
```
module.js:472
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
So the whole agent stopped working.

Beside the actual error, this shows that the current update mechanism is very fragile to update problems.

As suggested in my last comment in #19, I would love to switch to a container-based update mechanism which would require a regular build trigger for the image (i.e. nightly).

@pmeenan: Is it possible for you to set up such an automated docker hub build trigger?

**Comment by pmeenan** [comment]
I set up a cron job to trigger builds daily at midnight GMT.  I'll keep an eye on it to make sure it is working as expected.

Feel free to submit a PR to rip out all of the in-container update code (otherwise I'll make a pass at it later today).

One thing we probably need to figure out is a clean way to shut down the agent when killing the container so updates don't just terminate in the middle of a test.

**Comment by sburnicki** [comment]
I'll prepare the PR.
About gracefully killing:
The `signal_handler` could be connected to `SIGTERM` in addition to `SIGINT`. Then  I'd write the entrypoint so it propagates the signal to the wptagent process.

By default `docker stop` sends `SIGTERM` to the main process with a grace period of 10 seconds before sending `SIGKILL`. However, the grace period can also set to be longer, i.e. with `docker stop ----time=30 foo`. This way we could allow the agent to finish the test first within a given period.
