### ISSUE TITLE
Visual metrics are wrong for multistep tests

### ISSUE THREAD

**Issue by wildlyinaccurate** [WPO-Foundation/wptagent#221]
Example test: https://www.webpagetest.org/result/181121_VV_f2d9d147442eaab6c393c275ff1314e2/

Just taking a wild guess, but it's almost as if start render is being calculated as the time since the very first step, rather than the time since `logData 1`.

**Comment by pmeenan** [comment]
Can you try with debug=1&keepvideo=1 so we can get the debug log and raw video?  The filmstrip seems to agree with the visual metrics and it starts as blank so I'm assuming it was recorded correctly and not for all of the steps but it's not clear WHY it took 6 seconds to render.

**Comment by wildlyinaccurate** [comment]
Sure: https://www.webpagetest.org/result/181121_4K_680e58404fb67bff0421cc8351cc41c4/ (tested with Firefox to make sure it's not a Chrome issue)

Here's one with a simple navigate with the expected start render time: https://www.webpagetest.org/result/181121_SG_def5d100f534edfb08225fa2f6dea8dc/

**Comment by pmeenan** [comment]
Best as I can tell, it looks like setting the orange div over the page isn't working when you do document.body.innerHTML='' so it is measuring the time from when it starts getting things ready and not the actual navigation.

**Comment by pmeenan** [comment]
Figured it out. Seems like it thinks the page is 0px high so the orange dive doesn't cover the viewport. Working on a fix now

**Comment by wildlyinaccurate** [comment]
Thanks Pat! I was attempting to perform a git-bisect because this definitely used to work, but I'm yet to go far back enough to find a good commit. I'll leave it to you.

**Comment by pmeenan** [comment]
It seems to be specific to the page being tested for some reason. That part of the code hasn't changed in quite a while

**Comment by pmeenan** [comment]
Pushing the fix out now. FWIW, you should change your "execAndWait" to an "exec"

**Comment by zeman** [comment]
Thanks for the super fast turn around Pat. This was causing some Black Friday nervousness!
