### ISSUE TITLE
Error configuring traffic-shaping and unhandled exception in test run (no disk space left) while testing twitch.tv using Firefox Nightly

### ISSUE THREAD

**Issue by stephendonner** [WPO-Foundation/wptagent#231]
Hi Pat -

We're seeing problems again testing ```twitch.tv```, using Firefox Nightly, in both (especially) our private instance, as well as the public instance.

Public instance issues:
1. Test Error: Error configuring traffic-shaping: https://www.webpagetest.org/result/190108_3C_25163b62e60212168336e43a2a263d00/#run3 (test log: https://www.webpagetest.org/viewlog.php?test=190108_3C_25163b62e60212168336e43a2a263d00)
Snippet:
```
2019/01/08 18:08:30 - Test Created
2019/01/08 18:08:35 - Starting test (initiated by tester VM02-05-192.168.10.73)
2019/01/08 18:08:35 - Run 1 assigned to VM02-05-192.168.10.73
2019/01/08 18:08:35 - Run 2 assigned to VM03-03-192.168.10.82
2019/01/08 18:08:36 - Run 3 assigned to VM04-06-192.168.10.94
2019/01/08 18:09:24 - Test Run Complete. Run: 3, Cached: 0, Done: 1, Tester: VM04-06-192.168.10.94, Test Run Error: "Error configuring traffic-shaping"
2019/01/08 18:09:24 - Marked shard 3 as complete: {"3":true}
2019/01/08 18:09:24 - Extracting 48156 byte uploaded file '/tmp/phpS5s4fQ' to './results/19/01/08/3C/25163b62e60212168336e43a2a263d00'
2019/01/08 18:09:24 - Done Processing. Run: 3, Cached: 0, Done: , Tester: VM04-06-192.168.10.94, Test Run Error: "Error configuring traffic-shaping"
```
2. Test Error: Unhandled exception in test run: [Errno 28] No space left on device: https://www.webpagetest.org/result/190108_5F_9c2a2a9b3666437f89a29f540a6f8eaf/#run2 (and run3) (test log: https://www.webpagetest.org/viewlog.php?test=190108_5F_9c2a2a9b3666437f89a29f540a6f8eaf)
Snippet:
```
2019/01/08 08:58:49 - Test Created
2019/01/08 08:58:51 - Starting test (initiated by tester VM01-07-192.168.10.65)
2019/01/08 08:58:51 - Run 1 assigned to VM01-07-192.168.10.65
2019/01/08 08:58:52 - Run 2 assigned to VM02-08-192.168.10.76
2019/01/08 08:58:52 - Run 3 assigned to VM04-06-192.168.10.94
2019/01/08 09:01:54 - Test Run Complete. Run: 3, Cached: 0, Done: 1, Tester: VM04-06-192.168.10.94, Test Run Error: "Unhandled exception in test run: [Errno 28] No space left on device"
2019/01/08 09:01:54 - Marked shard 3 as complete: {"3":true}
2019/01/08 09:01:54 - Extracting 4439132 byte uploaded file '/tmp/phpoNFUDS' to './results/19/01/08/5F/9c2a2a9b3666437f89a29f540a6f8eaf'
2019/01/08 09:01:54 - Done Processing. Run: 3, Cached: 0, Done: , Tester: VM04-06-192.168.10.94, Test Run Error: "Unhandled exception in test run: [Errno 28] No space left on device"
```

/cc @jbuck @davehunt @soulgalore @wildlyinaccurate (anyone else seeing this, or something like it?)

**Comment by pmeenan** [comment]
Looks like the public agents have [~1.6GB of free disk](https://www.webpagetest.org/getTesters.php?f=html#Dulles). My guess is that the video capture for twitch ends up taking more space than that because of large auto-playing video in the view and the agent runs out of space.

It might be possible to add some checks while the test is running to kill the video capture if disk space starts to get too low or the video file gets too big (or both).  I expect something like 100MB is a sane upper limit for the video file beyond which useful information isn't being captured. Could just force video capture to stop at that point and let the test itself continue.  There might have to be protection added to the video processing as well when the frames are extracted.

**Comment by stephendonner** [comment]
@pmeenan thanks; there's also https://www.webpagetest.org/result/190108_Y4_fd547bfb52ca390d3d1b392fbd4d473d/ which you might have already seen/will get to:

3. (same?) disk-space issues?:
```
2019/01/08 21:37:48 - Test Created
2019/01/08 21:37:57 - Starting test (initiated by tester VM01-02-192.168.10.60)
2019/01/08 21:37:57 - Run 1 assigned to VM01-02-192.168.10.60
2019/01/08 21:38:02 - Run 2 assigned to VM04-07-192.168.10.95
2019/01/08 21:38:03 - Run 3 assigned to VM02-05-192.168.10.73
2019/01/08 21:42:53 - Test Run Complete. Run: 3, Cached: 0, Done: 1, Tester: VM02-05-192.168.10.73
2019/01/08 21:42:53 - Marked shard 3 as complete: {"3":true}
2019/01/08 21:42:53 - Extracting 1240770 byte uploaded file '/tmp/phpMIHDZK' to './results/19/01/08/Y4/fd547bfb52ca390d3d1b392fbd4d473d'
2019/01/08 21:42:53 - Done Processing. Run: 3, Cached: 0, Done: , Tester: VM02-05-192.168.10.73
2019/01/08 22:42:54 - Test run 1 has been running for 64 minutes on VM01-02-192.168.10.60, forcing done.
2019/01/08 22:42:54 - Test run 2 has been running for 64 minutes on VM04-07-192.168.10.95, forcing done.
2019/01/08 22:42:54 - Test has been running for 64 minutes and it has been 60.016666666667 since the last update, forcing the full test to finish.
```

https://www.webpagetest.org/viewlog.php?test=190108_Y4_fd547bfb52ca390d3d1b392fbd4d473d

Just posting this last one as a more-recent datapoint, FWIW; I'll also comment later here with either a new Issue about our private-instance specific issue(s), and, if it's helpful here, our various ```*timeout``` values (they are legion, for they are many).

(Sorry, that's more of a side note.)

**Comment by pmeenan** [comment]
Probably related. Running out of disk space can break a lot of things in unexpected ways.  I'll add a quick hack to limit the video to 100MB and to make sure the extracted frames stay under control as well.

**Comment by pmeenan** [comment]
I just pushed a change to limit the video file itself to 50MB. I had run one quick test and the twitch video was ~150MB.

Video processing MIGHT still be a problem if there is a lot of activity in the video. In the test I ran, the extracted video frames were ~100MB but if full size video frames are enabled or the video had a lot more frames it could explode quite a bit.

Hopefully the limiting of the video file itself keeps the extracted frames under control as well but I'm also looking into ffmpeg to see if I can tell it not to extract more than X frames (doesn't currently look like there is an easy way to do it).

**Comment by pmeenan** [comment]
Probably worth noting that the moz_log might also be the problem. In the test I just ran it was 1.2GB :(

We had made one attempt to use a reduced log level but it didn't have the necessary data. Might be worth looking again to see if there is a specific event that is filling the logs and if there is a way to filter it out.

If that doesn't work we can try enabling log rotation and run something in the background to compress the log files as they are rotated but keeping that in sync might be difficult.

**Comment by pmeenan** [comment]
or, I could also just suck it up and build new AMI's on larger disks instead of the 10GB images I'm currently publishing. 20GB should provide plenty of space.

**Comment by soulgalore** [comment]
For the MOZ log there's an open issue where the Mozilla team has done a change to make the log take less power to produce (and maybe also smaller?), they needed feedback to try that it worked but I haven't got around to try it out. @stephendonner you know which issue? I'm on my other computer and don't have access at the moment.

**Comment by pmeenan** [comment]
I know I was on one issue where they were trying to move the events that WPT needed out of log level 5 into log level 3 to make the logs a lot less verbose but some events were missed and WPT wasn't extracting the request data correctly so it isn't currently enabled.

**Comment by stephendonner** [comment]
Thanks, @pmeenan can confirm our twitch.tv et al timeouts are no longer a thing (at least, don't appear related to video - other tests have "random" timeouts from time to time).

<img width="2032" alt="screen shot 2019-01-10 at 10 15 09 am" src="https://user-images.githubusercontent.com/387249/50994594-8b578580-14d1-11e9-9a67-3a898702f840.png">

**Comment by stephendonner** [comment]
@soulgalore @pmeenan the "Using MOZ HTTP log adds a lot of overhead" bug is [bug 1452535](https://bugzilla.mozilla.org/show_bug.cgi?id=1452535).  I'll add a comment to try to resume working through that issue, but would love you two to comment, of course!
