### ISSUE TITLE
CDN and Hosting optimization checks take a long time on Windows EC2

### ISSUE THREAD

**Issue by wildlyinaccurate** [WPO-Foundation/wptagent#232]
Following up on that email about Windows tests taking a long time to run, I found this in some debug logs:

```
CDN check took 30.110 seconds
Hosting check took 30.078 seconds
```

That looks to me like a 30 second timeout on something - maybe DNS resolution? I've looked at dozens of tests so far and there is no hostname that is common to all of them, so I don't think it's just a few bad hostnames.

I can't replicate this on your Windows machine(s) in Dulles, so I'm taking a stab in the dark and assuming it's EC2-related.

**Comment by pmeenan** [comment]
It's bizarre that both the CDN and hosting checks took 30 seconds. The hosting check had a 30-second timeout that I just dropped to 5 seconds but it should have been independent of the CDN check which times out at 1 second for each lookup. Let me know if you see the times improve.  It's possible that one of the DNS lookup types wasn't working with the EC2 name servers with the Windows agents (NS or PTR probably) and was timing out.

**Comment by wildlyinaccurate** [comment]
Thank you! I'll keep an eye on the times. I'm a bit puzzled about why this started happening all of a sudden halfway through December. I wish Amazon kept a list of changes that might be relevant to certain services.

**Comment by wildlyinaccurate** [comment]
This has definitely alleviated the issues we were seeing (lots of tests waiting in a queue) - thanks Pat! 

![screenshot_2019-01-17 ec2 new agents datadog](https://user-images.githubusercontent.com/794263/51280596-f3174e80-1a44-11e9-808b-40779d43d4fd.png)

Still unclear what caused this in the first place, but presumably it's an EC2/Windows issue rather than WPT.
