### ISSUE TITLE
Is the "clearcache" command supported?

### ISSUE THREAD

**Issue by wildlyinaccurate** [WPO-Foundation/wptagent#238]
I noticed that the "clearcache" command is implemented in DevtoolsBrowser. Is this a "supported" command? I only ask because it's not mentioned in the scripting documentation or the README.

**Comment by pmeenan** [comment]
Yep, my documentation skills just suck. That said, it only works for Chrome.

**Comment by wildlyinaccurate** [comment]
Fantastic. I will start converting the scripting docs later this week and add it to the user/ directory when it's done.
