### ISSUE TITLE
broken doc complete times on android devices

### ISSUE THREAD

**Issue by nilskuhn** [WPO-Foundation/wptagent#245]
Hi,

I am observing measurements on android smartphones with broken doc complete times:
https://www.webpagetest.org/result/190228_A5_4299f604b470ea4c8c9080a69595181e/

We host our own devices in a private instance and observe similar effects on Samsung Galaxy S7 and Galaxy Tab A. The `loadEvent` of navigation timings (blue area in waterfall and values in the table) seem to be ok. Maybe one could just take start of loadEvent as doc complete? Are there cases where we don't have loadEvent navigation timings but doc domplete (measured by different method)?

Regards, Nils

**Comment by nilskuhn** [comment]
Here is another example where doc complete is 600ms earlier then loadEvent start:
https://www.webpagetest.org/result/190228_N7_52d6b8a42b570569d33a7dec99561144/1/details/#waterfall_view_step1

**Comment by pmeenan** [comment]
If you can reproduce it while running with debug=1 as a test option it would help.  docComnplete is measured externally from when the last top-frame frame complete message fires from dev tools. Usually the only time when it is off from loadEventStart is when the page does a javascript redirect in which case loadEventStart would be artificially low since it wouldn't include the time from before the redirect. That doesn't look like what happened in the first case though so it's possible that the frame navigation got linked to a different frame.

**Comment by nilskuhn** [comment]
Here is a result with debug=1
https://www.webpagetest.org/result/190228_H5_a9fb0df13b21e33d09fea31a00c9d127/

**Comment by nilskuhn** [comment]
Any chance to find the time to track this down?

I had a look in to the debug log and yes, there are several different `frameId`s. But I have no idea what could be the problem here and why this just happens on Android, while doc complete looks ok on iOS and desktop for the same page. 

Maybe we will use `loadEventStart` in [OpenSpeedMonitor](https://github.com/iteratec/OpenSpeedMonitor/) instead of doc complete.

**Comment by pmeenan** [comment]
Fix should be rolling out over the next hour. Sorry it took so long to look into.  It's one of those "how did this ever work and when did it break" kind of bugs.  

The agent was setting a flag that tells the server that the test was a "visual" test for all android tests. When that happens, the server uses the visual metrics as placeholders for the docTime and fully loaded times.  The agent now (correctly) only sets that flag when it is running a blackbox test (opera, UC, etc).

My guess is we used to use dev tools for screenshots and that it may have broken with a recent Chrome build, causing it to go down the adb screenshot path which was always used for the blackbox browsers.

**Comment by nilskuhn** [comment]
> It's one of those "how did this ever work and when did it break" kind of bugs.

I know these ones ;-)

Thanks for the fix!
