### ISSUE TITLE
Best practice running WPTAgent on Docker?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/wptagent#253]
Hi Pat,
i have a couple of questions about running the WPTAgent in Docker. We paused our old instance some days ago and started our Docker version but reverted back today since we got a lot of errors. And I think maybe I do something wrong?

We start our agent like this (the container is just a tagged version of the wptagent):

```
sudo modprobe ifb numifbs=1

sudo docker run -d \
  -e SERVER_URL="http://wpt.wmftest.org/work/" \
  -e LOCATION="us-east" \
  -e KEY="$SECRET" \
  --cap-add=NET_ADMIN \
  --shm-size=2g \
  --name wptagent \
  -v /etc/localtime:/etc/localtime:ro \
  wikimedia/wptagent:$VERSION
```

And today I saw a couple of problems:
1. Firefox isn't working for us ping @stephendonner you are a Docker agent user right It should work out of the box or am I missing something?
<img width="946" alt="Screen Shot 2019-04-10 at 8 58 49 AM" src="https://user-images.githubusercontent.com/540757/55859733-f36e4400-5b72-11e9-90c4-5a704fffb275.png">
2. Running for two days created >20000 zombie processes many that where Chrome. Is that the way it should be?:

```
root       432  0.0  0.0      0     0 ?        ZN   Apr09   0:00 [chrome] <defunct>
root       436  0.0  0.0      0     0 ?        Z    Apr09   0:00 [dbus-launch] <defunct>
root       439  0.0  0.0      0     0 ?        Z    Apr09   0:00 [WebExtensions] <defunct>
root       440  0.0  0.0      0     0 ?        Z    Apr09   0:00 [Web Content] <defunct>
root       441  0.0  0.0      0     0 ?        ZN   Apr08   0:01 [chrome] <defunct>
root       442  0.0  0.0      0     0 ?        ZN   Apr09   0:00 [chrome] <defunct>
root       443  0.0  0.0      0     0 ?        Zs   Apr09   0:00 [dbus-daemon] <defunct>
root       444  0.0  0.0      0     0 ?        Z    Apr09   0:00 [crashreporter] <defunct>
root       446  0.0  0.0      0     0 ?        Z    02:15   0:00 [dbus-launch] <defunct>

```
3. One side note: All metrics where the same switching to the Docker version except running emulated Chrome that made the metrics much faster, first visual change dropping 50%. Not that it is an issue, just interested if others seen the same.

Best
Peter

**Comment by soulgalore** [comment]
The most problematic is Firefox. It works fine for a while (that's why I didn't see anything) then it stops working. I've turned off all automatic updates (I think) but maybe I missed something.

**Comment by pmeenan** [comment]
Sorry, I don't use the agent in docker anywhere so I can't speak to the best practices.

This looks related: https://github.com/WPO-Foundation/wptagent/issues/61

**Comment by soulgalore** [comment]
Yeah I know but I was hoping @stephendonner or maybe @sburnicki have some input?

**Comment by pmeenan** [comment]
Did you try the --init command-line parameters the issue talked about? Not sure it fixes the issue but looks like it is relevant for fixing the zombie processes.


________________________________

**Comment by soulgalore** [comment]
I'll try that on Monday. I think the Firefox problem must be something else though.

**Comment by sburnicki** [comment]
TBH we don't run most production agents with docker, the benefit/trouble ratio was too low for us.

The only long-lived agents that run in docker are those for the Falkenstein location, but they only run Chrome and are causing trouble every now and then: They run out of disk space because logrotate cannot be spawned since there are two many zombie processes.

I experienced the zombie process problem in any project that runs chromium in docker, mostly e2e testing. I wasn't aware of the `--init` option as mentioned in #61 and will definitely test it.

Also, those agents don't provide Firefox testing, I don't know why but will look into that.

I will report any news when I enable Firefox and run the container with `--init`.

**Comment by soulgalore** [comment]
I've got around to try out `--init` yesterday and it has been running successfully for 20 hours with no zombie processes and Firefox working. I'll do a PR for the docs later today.

For the size problem, let see when we kept it running for a while. @sburnicki do you mount specific log dirs to outside of Docker? Worst case I can do as we did with Java applications in the 90's, restart once each night and just empty all volumes :D But it would be nice to have a nice setup for handling disk automatically, but maybe it will just without the zombies?

**Comment by sburnicki** [comment]
Our docker agents also look better with `--init` (zombie processes would usually appear with the first test). Maybe Firefox breaking was a side effect of that, but let's see. Once Pat enabled other browsers for Falkenstein, I'll schedule some FF tests and monitor if they break.

The logs causing problems are actually the syslogs :D Usually logrotate cares about this and is  regularly started by cron. What I found is that cron couldn't spawn a logrotate, because the system process limit was reached with all the zombie processes. So eventually that should also just be a long-term side effect of zombie processes.

**Comment by soulgalore** [comment]
I still get the problem with Firefox, this time it took one day though. I'm having a little hard time to follow the logs but maybe this is related?:
```
firefox: no process found
firefox: no process found
firefox-trunk: no process found
firefox: no process found
firefox-trunk: no process found
firefox: no process found
```

If remove the image/volumes and restart, it works again.

**Comment by soulgalore** [comment]
I talked with @stephendonner on IRC and they are not using the Docker version. @sburnicki any change you enabled FF or is it @pmeenan that needs to do it for your instance?

**Comment by sburnicki** [comment]
I checked our setup and asked @pmeenan via to enable Firefox on that location. When it's enabled I will start running FF tests to give you feedback.

**Comment by pmeenan** [comment]
@sburnicki I just added Firefox to the config and it [worked the one time I ran it](https://www.webpagetest.org/result/190426_AT_173fd9595ce2a1728a7df74f20d77c09/). Let me know if it starts failing and I need to remove it.

**Comment by sburnicki** [comment]
I just scheduled a test on that agent with Firefox and the first run went through. It will run a test every 30mins, so I will check over the weekend if it breaks.

**Comment by sburnicki** [comment]
The Firefox tests are still [running smoothly](https://demo.openspeedmonitor.org/eventResultDashboard/showAll?graphName=&alias=&_action_showAll=Show&selectedInterval=-1&selectedTimeFrameInterval=604800&from=2019-04-21T22%3A00%3A00.000Z&to=2019-04-29T21%3A59%3A00.000Z&selectedFolder=61&selectedPages=2&selectedMeasuredEventIds=1143&selectedBrowsers=3&selectedLocations=371&selectedConnectivities=1&selectedAggrGroupValuesUnCached=DOC_COMPLETE_TIME&trimBelowLoadTimes=&trimAboveLoadTimes=&trimBelowRequestCounts=&trimAboveRequestCounts=&trimBelowRequestSizes=&trimAboveRequestSizes=).

The docker agents are up for 13 days now, running the image `webpagetest/agent:release` with `--init`. I also see logs like
```
firefox: no process found
firefox-trunk: no process found
firefox: no process found
```
However, I think that might just be the output of attempting to kill leftover processes?
https://github.com/WPO-Foundation/wptagent/blob/744e2b26a80522b1981889e3d962c2de868f6f20/internal/firefox.py#L249-L252

According to
https://github.com/WPO-Foundation/wptagent/blob/744e2b26a80522b1981889e3d962c2de868f6f20/internal/firefox.py#L195-L196

The error you see in the WPT GUI occurs in the try block above these lines. So you should find "Error starting Firefox" in your logs and maybe you find something suspicious in the lines before that, when wptagent actually tries to start firefox and connect to it via marionette?

**Comment by soulgalore** [comment]
Thanks @sburnicki , I'll try it out on Friday again when I'm back at work. The thing is sometimes it took just one hour, sometimes a day before it happened. I'll check the log again when it fails, last time it was just a myriad of messages, it was hard to see anything except the HTML error in https://github.com/WPO-Foundation/wptagent/issues/253#issue-431349241. But we run Firefox continuously every hour, I wonder if that could be a thing somehow.
