### ISSUE TITLE
Error Unhandled exception in test run: 'video_file' on mobile agents

### ISSUE THREAD

**Issue by bbraz** [WPO-Foundation/wptagent#264]
When running a test on the mobile agent with Capture Video disabled, we are getting a 
"Test Error: Unhandled exception in test run: 'video_file'" message.

This can be reproduced on webpagetest.org and here is a sample:
http://webpagetest.org/result/190523_2G_3a47e071e5124058ecaf785ed810bf50/

Let me know if you need further information.

**Comment by pmeenan** [comment]
Even with video disabled it still captures video locally to calculate Speed Index and the other visual metrics. Looks like somewhere in the code it isn't checking to see if the file name was cleared and it is throwing an exception.  Trying to reproduce it now with the debug logging enabled so I can get the call stack - should be an easy fix.

**Comment by pmeenan** [comment]
Looks like I was wrong and video capture is only always-on for Desktop. Found the case where it wasn't being handled properly and added the necessary checks. It should be picked up by the public agents within the next hour as they auto-update.

**Comment by bbraz** [comment]
Awesome! Thanks!
