### ISSUE TITLE
Test Error: Unhandled exception in test run: 'video_file'

### ISSUE THREAD

**Issue by reganp** [WPO-Foundation/wptagent#28]
This is happening with the latest version of wptagent, alongside ImageMagick with legacy tools on Windows O/S.

There is no test result data.

I get the following stack trace from the wptagent.py: 

15:47:55.835 - Connect to dev tools websocket Error: [Errno 10061] No connection
 could be made because the target machine actively refused it
15:48:11.118 - Unhandled exception in test run: 'video_file'
Traceback (most recent call last):
  File "C:\wptagent-new\wptagent\wptagent.py", line 117, in run_single_test
    browser.run_task(self.task)
  File "C:\wptagent-new\wptagent\internal\chrome_desktop.py", line 112, in run_t
ask
    DevtoolsBrowser.run_task(self, task)
  File "C:\wptagent-new\wptagent\internal\devtools_browser.py", line 162, in run
_task
    self.on_stop_recording(task)
  File "C:\wptagent-new\wptagent\internal\chrome_desktop.py", line 134, in on_st
op_recording
    DesktopBrowser.on_stop_recording(self, task)
  File "C:\wptagent-new\wptagent\internal\desktop_browser.py", line 261, in on_s
top_recording
    if os.path.isfile(task['video_file']):
KeyError: 'video_file'
SUCCESS: Sent termination signal to the process "chrome.exe" with PID 2344.
SUCCESS: Sent termination signal to the process "chrome.exe" with PID 3800.
SUCCESS: Sent termination signal to the process "chrome.exe" with PID 3848.
ERROR: The process "chrome.exe" not found.

**Comment by pmeenan** [comment]
Sorry about that.  Looks like a failed check related to the new video capture and processing on Linux.  Should be fixed now.

**Comment by reganp** [comment]
Yip looking good now thanks.
