### ISSUE TITLE
Using Firefox I'm seeing anti-tracking requests before initial connection

### ISSUE THREAD

**Issue by Nooshu** [WPO-Foundation/wptagent#284]
Testing a site using `Tester: London-89.107.60.22`, Firefox on a 3G connection I've started to see tracking protection requests before the initial connection is established. These are to the following URL: `https://tracking-protection.cdn.mozilla.net/block-flashsubdoc-digest256/`. This has happened while testing both `3G` and `3G Fast`.

An example of the waterfall I'm seeing can be seen below:

![Screen Shot 2019-09-09 at 13 47 12](https://user-images.githubusercontent.com/1223960/64534435-60962900-d30d-11e9-806c-c4535d760ce0.png)

Links to example tests where they can be seen are below:
- [One](https://www.webpagetest.org/result/190909_RM_fb4e479d6bfb4f497c1dab2e91525562/5/details/#waterfall_view_step1)
- [Two](https://www.webpagetest.org/result/190909_T4_95af0a1b75a7cc23d0f7c64bfb171785/8/details/#waterfall_view_step1)
- [Three](https://www.webpagetest.org/result/190909_RM_fb4e479d6bfb4f497c1dab2e91525562/1/details/#waterfall_view_step1)
- [Four](https://www.webpagetest.org/result/190909_RM_fb4e479d6bfb4f497c1dab2e91525562/7/details/#waterfall_view_step1)

**Comment by soulgalore** [comment]
Yeah, we see this too, here's an example: 
https://webpagetest.org/result/191202_AQ_840979ea2e9aa55654756806b1a8a46f/1/details/#waterfall_view_step1

I think something changed in Firefox settings between releases. @stephendonner can you help us in the right direction?

**Comment by soulgalore** [comment]
This seems to map in time when Enhanced Tracking Protection was turned in by default?

**Comment by Nooshu** [comment]
> This seems to map in time when Enhanced Tracking Protection was turned in by default?

Yes I believe it was around the same time that this was rolled out (version 69).

**Comment by pmeenan** [comment]
It's a bit of a heavy hammer but I added os-level blocking for the tracking list domains since none of the prefs seem to actually block it.  While I was in there I also fixed the "waiting" time for the Firefox waterfalls.

Should look a lot better now: https://webpagetest.org/result/191203_FA_8dcdee9a8d99d4c7e6100eb0a651ee5d/1/details/#waterfall_view_step1
