### ISSUE TITLE
First View: Test Error: Error configuring traffic-shaping - Docker

### ISSUE THREAD

**Issue by etlnibn** [WPO-Foundation/wptagent#289]
I am quite new here - so please be gentle!

I am following the guide at https://medium.com/@francis.john/local-webpagetest-using-docker-90441d7c2513 and I am suffering the classic traffic shaping error which has been discussed in [previous threads](https://github.com/WPO-Foundation/wptagent/issues/133) and apparently resolved.

I am running on Ubuntu 18.04 - when I check in "/install" everything looks normal.

From [Issue 89](https://github.com/WPO-Foundation/wptagent/issues/89) I tested the advice to run the command `sudo modprobe ifb numifbs=1` - but tests always result in the same "traffic shaping" error.

The recommendations in first article mentioned relate to OSX but that should not be necessary on Linux from what I understand - so now I am at a bit of  a loose end. I did try them and they worked but I need traffic shaping and that advice is all about how to remove the traffic shaping options.

In [issue 133](https://github.com/WPO-Foundation/wptagent/issues/133) the recommendation was to download the latest build but that was from 2018 and this is 2019 and I just ran the following so presumably that is not the problem in my case as I seem to be getting the latest builds.

```
- $ docker pull webpagetest/server
- $ docker pull webpagetest/agent
```

Here is what I am running for agent:
```
docker run -d -p 4001:80 \
   --network="host" \
   -e "SERVER_URL=http://localhost:4000/work/" \
   -e "LOCATION=Test" \
   -e "SHAPER=none" \
   --cap-add="NET_ADMIN" \
   webpagetest/agent

```
 I tried the options in [issue 89](https://github.com/WPO-Foundation/wptagent/issues/89) and that does not seem to have resolved the issue. 

Any help gratefully appreciated!
 
![Screenshot from 2019-10-10 19-54-28](https://user-images.githubusercontent.com/4129275/66593817-0bf9fe00-eb98-11e9-95b6-caae7ecdb306.png)

**Comment by etlnibn** [comment]
I resolved this myself using the following settings. First the server options 

`docker run -d -p 4000:80 --rm --name wpt-server webpagetest/server `

Then this ….

`sudo modprobe ifb numifbs=1 `

Finally this for the agent. It seems that this is the bit that I was doing incorrectly.

`sudo docker run -d --name wpt-agent -vvvv -p 4001:80 --network="host" -e "SERVER_URL=http://localhost:4000/work/" -e "LOCATION=Test" --cap-add=NET_ADMIN  webpagetest/agent`

**Comment by tung-nt-niteco** [comment]
Hi,

We encountered this problem also, and we run all recommended commands above:
sudo modprobe ifb numifbs=1
and
ip link set ifb0 up
and
sudo docker run --ipc=host -d --name wpt-agent00 -e "EXTRA_ARGS=--shaper none" -vvvv --network="host" -e "SERVER_URL=https://servergoeshere/work/" -e "LOCATION=locationgoeshere" -e KEY="keygoeshere" -e NAME="Speedcurve Agent Docker 00" --cap-add=NET_ADMIN webpagetest/agent

but we still got error "Test Error: Error configuring traffic-shaping" (and not only the first test failed).
Could you please advise?

**Comment by tung-nt-niteco** [comment]
Hi again, I see that I do not need -e "EXTRA_ARGS=--shaper none"

So the following commands work :)
sudo modprobe ifb numifbs=1
and
sudo docker run --ipc=host -d --name wpt-agent00 -vvvv --network="host" -e "SERVER_URL=https://servergoeshere/work/" -e "LOCATION=locationgoeshere" -e KEY="keygoeshere" -e NAME="Speedcurve Agent Docker 00" --cap-add=NET_ADMIN webpagetest/agent

**Comment by tung-nt-niteco** [comment]
It seems that I also had to disable traffic-shaping on WPT server (in locations.ini, set connectivity to the one that has no traffic-shaping defined in connectivity.ini)

**Comment by tung-nt-niteco** [comment]
After further investigation, we have found that if we separate docker agents to separate machines (1 agent/1 host), it will solve the traffic-shaping problem, and we do not have to disable this feature. Worked perfectly now.

**Comment by skmohammadi** [comment]
After a lot of struggle, I found that:

- Traffic-Shaping relies on the IFB network interface, so the agent server network should support it.
- In the case of WSL2, IFB doesn't seem to be available.
- It may be necessary for Docker containers to run Agent server as follows (notice to use of **--cap-add=ALL**)

```
docker run -d --cap-add=ALL -p 4001:80 --network="host" -e "SERVER_URL=http://localhost:4000/work/" -e "LOCATION=Test" webpagetest/agent
```
It worked like a charm for me.
