### ISSUE TITLE
Wrong path to getwork.php

### ISSUE THREAD

**Issue by yoavweiss** [WPO-Foundation/wptagent#3]
I'm trying to get wptagent to run on Linux with a private server and ran into an issue where the agent is polling the wrong server URL for work.
Instead of sending requests to `/work/getwork.php` they are sent to `/getwork.php` resulting in server errors.

I fixed it locally by changing the path at `internal/webpagetest.py:get_test`. I'm not sure if this is a generic issue, or said path has changed in the latest WPT server.

**Comment by yoavweiss** [comment]
Same issue (and same local solution) for `workdone.php`

**Comment by pmeenan** [comment]
Probably confusion (and docs/help that need better text) because the server command line needs to include the /work part of the path: 

```
--server http://www.webpagetest.org/work/
```
