### ISSUE TITLE
Docker image doesn't run any more

### ISSUE THREAD

**Issue by wildlyinaccurate** [WPO-Foundation/wptagent#303]
I'm guessing there have been some gcc updates pulled into Ubuntu 18.04, because starting the agent now throws this error:

```
Traceback (most recent call last):
  File "/wptagent/wptagent.py", line 939, in <module>
    main()
  File "/wptagent/wptagent.py", line 930, in main
    agent = WPTAgent(options, browsers)
  File "/wptagent/wptagent.py", line 24, in __init__
    from internal.webpagetest import WebPageTest
  File "/wptagent/internal/webpagetest.py", line 21, in <module>
    import ujson as json
ImportError: /usr/local/lib/python2.7/dist-packages/ujson.so: undefined symbol: Buffer_AppendShortHexUnchecked
```

It doesn't look like ujson is supported any more, so I followed the advice of [this comment](https://github.com/esnme/ultrajson/issues/271#issuecomment-375020621) and installed a patched fork, which fixed the issue.

I can submit a patch to the Dockerfile that installs from this fork if you're okay with that. But I'm guessing this will eventually affect more than just the Docker image.

**Comment by pmeenan** [comment]
:/ 

I just landed a change to fallback to json if ujson isn't available so at least the agents will still work.  JSON parsing speed is critical to the agent's performance for both trace and devtools messages so long-term we need to find another library that is supported, fast for trace parsing and can be dropped in.

If you don't mind updating the docker image in the meantime it would be appreciated.

**Comment by wildlyinaccurate** [comment]
No prob, I'll submit the patch now.

Potentially annoying question: is a Python 3 migration on the cards at some stage? [orjson](https://github.com/ijl/orjson) claims to be the new fast parser on the block. Not to mention Python 2.x is EOL in _\<checks watch\>_ 2 weeks.

**Comment by pmeenan** [comment]
Yes, Python 3 is on my mind but I'm not quite sure how I want to pull it off yet.  Probably won't happen before EOL though.

I'm currently planning on going through and making the same code work on both 2.x and 3.x so it can be the same code base and we don't need to split it and maintain 2 branches. I've had pretty good luck doing that with a few smaller projects and there isn't too much that I think will need patching.  The main ones are monotonic (which can be replaced by a stub that calls the right monotonic under the covers) and the message queues.

**Comment by pmeenan** [comment]
Main concern with orjson is that it's not a drop-in replacement and it serializes to byte strings instead of strings and that would probably kill the drop-in ability. Though it might be worthwhile to use it in a few places if it is available and just use the default json library where performance isn't as critical.

**Comment by wildlyinaccurate** [comment]
I don't have much experience migrating to Python 3 outside of a few trivial 2to3 conversions, but I'd be happy to lend a hand if/when you're looking into it. I could set up an integration test harness or something like that if you think it'd be useful.
