### ISSUE TITLE
[Question] Support for Chromium Edge

### ISSUE THREAD

**Issue by edwincoronado** [WPO-Foundation/wptagent#308]
Hello, 

Now that Microsoft is about to [release an official Chromium Edge](https://www.extremetech.com/computing/304783-microsoft-will-push-chromium-edge-out-on-wednesday) build. Is there plans in the roadmap to support this browser in WPT? Could the chrome driver also work for Chromium Edge?

Thanks!

**Comment by pmeenan** [comment]
Dev and Canary are already supported and available on the Windows instances (Dulles, Dulles Thinkpad). When stable is released it will also be added.

**Comment by edwincoronado** [comment]
> Dev and Canary are already supported and available on the Windows instances (Dulles, Dulles Thinkpad). When stable is released it will also be added.

Thanks @pmeenan ! We run private instances in our company, will this change to support the production Chromium Edge will be pushed as part of a release for the `wptagent` repo?

**Comment by pmeenan** [comment]
Yes. It should already work if you specify it in browsers.ini but the
autodetecting will be added so it will just work out of the box.

**Comment by edwincoronado** [comment]
Thanks @pmeenan !
