### ISSUE TITLE
Lighthouse reports failing

### ISSUE THREAD

**Issue by ordinary-joe** [WPO-Foundation/wptagent#310]
When running WPT, lighthouse reports are failing. WPT examples as follows, with different locations and different phone emulation. https://webpagetest.org/result/200120_65_92bd842dcbdb470d73d9d268cd92146b/ and https://webpagetest.org/result/200120_VJ_0844d7901e999da64b4d7b86fab74bee/

**Comment by pmeenan** [comment]
It's a little strange. When I re-run your tests I can reproduce the failure but when I create new tests through the UI it works.  Looking at the raw test config data for your tests, it looks like the "password" field was filled out in the auth tab of the advanced settings and a password was included with the test.

I verified that filling out the password field in the auth tab breaks the lighthouse test (I'll investigate why it isn't just ignored).

Is it possible that you have an extension or something that autofilled the password without you knowing?  I just added attributes to the form fields to prevent it from auto-filling (for extensions that don't ignore it).

**Comment by ordinary-joe** [comment]
You're right...there was a password entered into the Auth tab, in both my personal WPT account and the public account when I used it. No idea how it got there. i removed the password from the test config and all seems to be fine now. Odd. Thanks very much for the resolution.
