### ISSUE TITLE
Error processing log file

### ISSUE THREAD

**Issue by GrigoreMihai** [WPO-Foundation/wptagent#312]
We are trying to setup a test location in order to host it (I followed your docs for hosting a test location and followed every step while configuring), but while testing it I run into the following error:

```
Error processing log file
Traceback (most recent call last):
  File "/root/wptagent/internal/support/firefox_log_parser.py", line 66, in process_logs
    self.process_log_file(path)
  File "/root/wptagent/internal/support/firefox_log_parser.py", line 131, in process_log_file
    f_in = gzip.open(path, GZIP_READ_TEXT)
NameError: global name 'GZIP_READ_TEXT' is not defined
Marionette exception navigating to about:blank after the test
Traceback (most recent call last):
  File "/root/wptagent/internal/firefox.py", line 324, in run_task
    self.marionette.navigate('about:blank')
AttributeError: 'NoneType' object has no attribute 'navigate'

```
The operating system is centos 7. 
We tested the agent with a private instance and only a part of the test info made it to the page.
If you want any more details feel free to ask.

**Comment by pmeenan** [comment]
The log file error was just fixed (wow, no idea how that got through, thanks).

That feels like a different problem than the testing problem where Marionette doesn't exist and is throwing an exception (unless it is a downstream error from parsing the log).
