### ISSUE TITLE
LCP missing for some URLs

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/wptagent#322]
Hi @pmeenan, unsure if this is related to #277 but we're seeing quite a few tests with missing LCP values or a value of 0. Here's a couple of examples on public:

https://www.webpagetest.org/jsonResult.php?test=200211_YR_5ca21e454fe7e42d7bcd6f80e4fd2d09&pretty=1&requests=0

https://www.webpagetest.org/jsonResult.php?test=200210_DP_662cd1f6118e586e1fe3416532e28929&pretty=1&requests=0

Running a performance trace in Chrome directly I do get LCP for these URLs. It only seems to affect some URLs. You can see an example in the new Benchmarks resource we just launched where LCP is missing for some URLs or often reported as 0.

https://speedcurve.com/benchmarks/europe/media/fast/largest-contentful-paint/

Is this to be expected with the LCP candidate being invalidated for some reason?

**Comment by pmeenan** [comment]
Looks like the problem has changed a little bit. There aren't invalidations anymore but there are multiple LCP candidate events. In this case there are 2 candidates for the main frame and one for a subframe. The current trace parsing just stores the latest of a given event and in this case that's the subframe (in which case it gets ignored by the processing in the end which only outputs main frame metrics).

The 3 candidates stored in that example are 2 text and 1 image paint and the image paint is in a subframe.

My current plan is to have the agent log all of the candidates that aren't invalidated and then have the web side's page_data.php do additional processing that if the event name includes "Largest" only output the event with the biggest size that was in the main frame.

Odds are all of this is going to be pretty fragile until LCP is exposed to the DOM in paint timing and can be extracted directly.

**Comment by pmeenan** [comment]
Should be fixed now but let me know if you run into any more cases.

Here is the agent change: https://github.com/WPO-Foundation/wptagent/commit/371ab83016e8c6ca9bb2c961b72ee557db991a24

And here is the php server change: https://github.com/WPO-Foundation/webpagetest/commit/b1914a344df00ba07e67e76c21e30e77714e367b

**Comment by zeman** [comment]
Thanks Pat, we'll update our agents and keep an eye on it.
