### ISSUE TITLE
Digital Ocean Spaces CDN not recognized

### ISSUE THREAD

**Issue by vdswouter** [WPO-Foundation/wptagent#339]
Hi there,

We use DigitalOcean Spaces to host the static assets of the websites we build.
We always turn on their option for CDN-hosting, but WPT does not recognize it as a CDN.

There are many server-locations to host your spaces from, but they all end in the `digitaloceanspaces.com`-domain.

As it is a user-setting not everything hosted from that domain is CDN-hosted.

More information: https://www.digitalocean.com/docs/spaces/how-to/enable-cdn/

**Comment by pmeenan** [comment]
It looks like ".cdn.digitaloceanspaces.com" is the CDN entry point to spaces (not all of spaces is a CDN).  I just added it and it should be picked up over the next hour.
