### ISSUE TITLE
Newlines on Mac for wptagent.py

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/wptagent#34]
Hi Pat, 
and thanks for adding Mac OS X support, that is great for doing fixes and PRs :) I've started last week getting Docker to work on my Mac but it was a pain since traffic shaping will not work and some configure issues that's been talked about in other issue.

When I try to start my agent on my Mac I get *env: python\r* and I fixed it by changing newlines with *dos2unix wptagent.py* but I guess there's a better way to do it so it works out of the box?

Best
Peter

**Comment by pmeenan** [comment]
Argh.  Not sure how those snuck in (or how it was working on my Mac) but I just cleaned up the line endings on the file.
