### ISSUE TITLE
Script causing test errors on Google Chrome

### ISSUE THREAD

**Issue by josebolos** [WPO-Foundation/wptagent#345]
I've been having trouble for a few weeks with one of our tests that we run on SpeedCurve, but I've managed to replicate the problem on webpagetest.org, so I'm reporting it here.

This test uses scripting and its purpose is to test a widget that was present on the page. This widget was removed from the page a while ago, but I forgot to disable the test so it was still running.

```
combineSteps
navigate	https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-1058-1#Decs
execAndWait	document.querySelector("[data-target='Declarations']").click();
execAndWait	document.getElementById("App1").scrollIntoView();
```

Running the test on webpagetest.org using Chrome causes the following error:
```
First View
(Test Error: Unhandled exception in test run: coercing to Unicode: need string or buffer, int found)
```

Example test using Chrome:
https://www.webpagetest.org/result/200522_KQ_381f39e0682e9bb32c141375a2e83b44/

Running it on SpeedCurve shows a slightly similar error, I'm guessing because the version of  wptagent is not exactly the same:
```
First View
(Test Error: Unhandled exception in test run: cannot concatenate 'str' and 'int' objects)
```

The waterfall view seems broken, it looks like WPT fails to calculate the initial time properly so most of the content of the waterfall is out of view. I'm guessing the `combineSteps` has something to do with it.

![image](https://user-images.githubusercontent.com/1792637/82666316-9249e880-9c2d-11ea-8ca1-8c5d2272cee6.png)

Running the test on Firefox doesn't show any errors:
https://www.webpagetest.org/result/200522_0E_efb84ee7078bc8fc976e3b4a1525abd0/

**Comment by pmeenan** [comment]
Thanks. Repro cases are gold for finding and fixing issues.  Fixed the exception, looking into the waterfall issues.
