### ISSUE TITLE
DNS lookup missing in waterfall on connection coalescing

### ISSUE THREAD

**Issue by gmetais** [WPO-Foundation/wptagent#346]
Hi Pat,

You can notice on [this waterfall](https://www.webpagetest.org/result/200519_W0_5e452301812475bc9ec6775420ba2466/1/details/) that there is a "connection coalescing" in action between www.begeek.fr and media.begeek.fr domains. I'm not a specialist, but it looks like the DNS lookup for the subdomain should appear.

Thanks!

**Comment by pmeenan** [comment]
Fixed: https://www.webpagetest.org/result/200524_Tx3P_64222391c715cd5adcdd4354f777fb24/1/details/#waterfall_view_step1

It will take an hour or so to roll out to production
