### ISSUE TITLE
Connection view from the Firefox agent looks broken

### ISSUE THREAD

**Issue by gmetais** [WPO-Foundation/wptagent#347]
As discussed, the connection view at the end of [this waterfall](https://www.webpagetest.org/result/200522_5S_431c0733576c1be1429508753aaa2968/1/details/#waterfall_view_step1) is broken. All lines are merged into a unique line.

This is not a matter of which page I test, all sites produce the same result when the Firefox agent is chosen.

<img width="942" alt="Capture d’écran 2020-05-23 à 01 08 32" src="https://user-images.githubusercontent.com/498031/82715129-246ee280-9c68-11ea-9787-e6f894bdb50f.png">

(Thank you so much for your tool!)

**Comment by pmeenan** [comment]
This is now fixed and will be rolling out over the next hour: https://www.webpagetest.org/result/200524_TxRC_0d033079876e68cd68efb7c3eca1a4a1/1/details/#waterfall_view_step1
