### ISSUE TITLE
Minimum test duration ignored when it encouters a 404

### ISSUE THREAD

**Issue by Nooshu** [WPO-Foundation/wptagent#349]
Context: This may be a work-around to allow performance testing of 404 pages.

![waterfall](https://user-images.githubusercontent.com/1223960/82841487-32be3800-9ece-11ea-9645-2bd05b65ac96.png)

Test page [here](https://www.gov.uk/this-is-a-404).
Example failing test [here](https://www.webpagetest.org/result/200519_6B_73ef7a0df686d0d732f204167d4baa0e/1/details/#waterfall_view_step1).

**Comment by pmeenan** [comment]
Should be rolled out to prod over the next hour: https://www.webpagetest.org/result/200601_TxAD_8e321e49f1efcfd0e8dde0e058b5d843/
