### ISSUE TITLE
Firefox 76 showing unexpected connection requests

### ISSUE THREAD

**Issue by Nooshu** [WPO-Foundation/wptagent#351]
I ran a test on London Atlantic, FF76 and I'm seeing a few unexpected requests:

![connection](https://user-images.githubusercontent.com/1223960/83031987-28668000-a02d-11ea-8c6c-2365f683b7d9.png)

Seeing requests to:
• https://firefox.settings.services.mozilla.com
• https://snippets.cdn.mozilla.net
• `asset-manifest.json` 404

Test can be [seen here](https://www.webpagetest.org/result/200527_RB_4b69105b013f609738e6608f43f75210/)

Only seen in Firefox, Chrome is okay. `assets-manifest.json` is only seen in Firefox too, So i'm unsure what is happening there. Chrome test for comparison [here](https://www.webpagetest.org/result/200527_TX_6e093fb21b836c0b3eae8a718cd35686/1/details/#waterfall_view_step1)

**Comment by pmeenan** [comment]
Just added some prefs and domain blocks to block the new activity. We'll see in an hour or so if that was enough to kill the new activity. https://github.com/WPO-Foundation/wptagent/commit/b635b7b86316f7c6bc3e8f08802b1631cc5413d5

**Comment by Nooshu** [comment]
Verified fixed. thanks @pmeenan!

![fixed](https://user-images.githubusercontent.com/1223960/83043740-24d9f580-a03b-11ea-8143-348377ffe41a.png)

Tests [seen here](https://www.webpagetest.org/result/200527_AS_ced4d55e5b9fca27a6dec68fc7019730/5/details/#waterfall_view_step1).
