### ISSUE TITLE
Expose minimum test duration for WPT scripting.

### ISSUE THREAD

**Issue by Nooshu** [WPO-Foundation/wptagent#353]
#349 allowed 404 pages to be tested via the use of the 'min test duration' workaround, but this currently isn't possible via scripting alone. 

Example usage:
```
log 1
time 2
navigate https://www.site.com/this-is-a-404-page
```

Also related: [#1275](https://github.com/WPO-Foundation/webpagetest/issues/1275)

**Comment by pmeenan** [comment]
Just pushed to the release branch and should roll out to the public instance over the next hour.
