### ISSUE TITLE
Largest Contentful Paint computation discrepancy

### ISSUE THREAD

**Issue by patrickhulce** [WPO-Foundation/wptagent#355]
I recently bumped into a page with a fairly sizable LCP discrepancy between Lighthouse and WPT. I dug into the trace a bit and found an LCP event that's later than what WPT reports. Poking around the code it looks like it should be sorting and respecting the Invalidate events properly, so I'm not sure what's going on.

![image](https://user-images.githubusercontent.com/2301202/84083603-95700300-a9a7-11ea-898a-e0c4f96dd2ca.png)
![image](https://user-images.githubusercontent.com/2301202/84083778-e5e76080-a9a7-11ea-9d83-61aa0f36224e.png)

https://github.com/WPO-Foundation/wptagent/blob/6f4756311ce48d1ecd9925d78d2f3c00cb1148fe/internal/support/trace_parser.py#L316-L322

Anything immediately jumping out for where I or Lighthouse might be misunderstanding or WPT might be off? 

I've been asked explicitly not to make the URL public but can share the WPT test with you privately @pmeenan :)

**Comment by pmeenan** [comment]
Looking at the trace events:

```json
[
{"name":"LargestContentfulPaint","tts":2771537,"args":{"frame":"63196382373AC2C897C990897A3C4285","data":{"navigationId":"E7B3BE155EA942F0CEAA640C72C6105D","nodeId":29,"isMainFrame":true,"candidateIndex":2,"type":"text","size":7665}},"pid":17215,"ts":7767025841,"cat":"loading,rail,devtools.timeline","tid":17231,"ph":"R","dur":1},
{"name":"LargestContentfulPaint","tts":1017428,"args":{"frame":"63196382373AC2C897C990897A3C4285","data":{"navigationId":"E7B3BE155EA942F0CEAA640C72C6105D","nodeId":11,"isMainFrame":true,"candidateIndex":1,"type":"text","size":7665}},"pid":17215,"ts":7764489714,"cat":"loading,rail,devtools.timeline","tid":17231,"ph":"R","dur":1}
]
```

Both LCP events have the same size. WPT only updates the candidate if the size of a new LCP is > than the previous largest.  I'm willing to change it to match lighthouse but I'm a bit suspicious of the second event since it's no larger than the first one - why would it be the "first" "largest"?

**Comment by pmeenan** [comment]
btw, those are the post-processed candidate events from WPT. I'll check the raw LCP candidate events in the morning.

**Comment by patrickhulce** [comment]
Ah, interesting there is no `largestContentfulPaint::Invalidate` event even though there *are* several `NavStartToLargestContentfulPaint::Invalidate::AllFrames::UKM`.

I wouldn't expect that to happen, I wonder whether the invalidation is real or not then. 

I agree in the absence of an invalidate Lighthouse should not pick the later event if the size is equivalent and that's a bug in LH not WPT.

**Comment by tkadlec** [comment]
Given how much has changed with the way Chrome measures LCP since this time, I'm going to close this and, if we stumble on an issue like this again, we can file a new issue.
