### ISSUE TITLE
Results not being capture correctly when navigating between pages in SPA

### ISSUE THREAD

**Issue by waltertlatenchi-revolve** [WPO-Foundation/wptagent#357]
I'm trying to capture performance results when navigating from homepage to a product list page but the metrics, screenshot and filmstrip are not being capture correctly.

I am running the following script:
```
logData	0
setCookie	https://www.revolve.com	moov_pwa=true
navigate	https://www.revolve.com/r/mobile/index_women.jsp?moov_debug=true
logData	1
execAndWait	document.querySelector("[href*='/br/3699fc/']").click()
```
webpagetest results link: https://www.webpagetest.org/result/200623_4S_b0a1d9a7155f34c7b31279047967f18b/

webepagetest results with logdata turned off: https://www.webpagetest.org/result/200617_45_d270013d068df8dfea1a2557edbab2b6/

The final screenshot should have images loaded. The page seems to transition to product list page but the images never load. This script seemed to be working fine initially but then it stopped maybe after 4/22/2020.

These are the results I would get when it was working: https://wpt1.speedcurve.com/result/200422_HC_7fb335e2465f401242c8705b9d6ef6d1/
Start Render, Speed Index, Screenshot, and Filmstrip seem accurate.

**Comment by pmeenan** [comment]
My guess is that some part of the loading after firing the event is causing more than a 2 second gap in the network activity.  You can force the second step to wait for a minimum amount of time with setMinimumStepSeconds or change the 2 second activity timer with setActivityTimeout.

```
logData	0
setCookie	https://www.revolve.com	moov_pwa=true
navigate	https://www.revolve.com/r/mobile/index_women.jsp?moov_debug=true
logData	1
setMinimumStepSeconds	10
execAndWait	document.querySelector("[href*='/br/3699fc/']").click()
```

Seemed to work: https://www.webpagetest.org/result/200623_CD_0311859adb7b8db6ace97fe89175db83/

The connection to is4.revolveassets.com took close to 4 seconds to establish which is why the test aborted early.

**Comment by waltertlatenchi-revolve** [comment]
@pmeenan Thank you for the response. I tried this script on other environments but it seems to fail. Is that to be expected? For example,

**iPhone 6s iOS 13 - Cable**
https://www.webpagetest.org/result/200623_WQ_515fe40929472fd1c2f941e40b32f8c1/

**Moto G4 - Chrome - Cable**
https://www.webpagetest.org/result/200623_Z3_e94eb997d0a26d3f455d3fd005a8badc/

**Moto G4 - Chrome - Emulated Motorola G (gen 4) - Cable - Mobile**
https://www.webpagetest.org/result/200623_V0_87813b554fbc6adb89a1feb9f9ed3b3e/

It did worked in this environment:
**Thinkpad T430 - Chrome - Emulated Motorola G (gen 4) - Cable - Mobile**
https://www.webpagetest.org/result/200623_6E_3c1eb200fa7c8ab4c4e0c3bf9565c683/

I was hoping to get it to work on an iPhone device.

**Comment by waltertlatenchi-revolve** [comment]
Tests now seem to be working fine on SpeedCurve.
