### ISSUE TITLE
Filmstrip view images has wrong dimension for Firefox/Mac OS X

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/wptagent#36]
Are they generated through VisualMetrics, meaning the video is also wrong? Is there a way to keep/get hold of the original video? I can see the path in the log but I guess it is moved to the server?

<img width="962" alt="screen shot 2017-08-28 at 10 44 22 am" src="https://user-images.githubusercontent.com/540757/29766103-ec764168-8bdd-11e7-8fc2-1e37f9e008a0.png">

The screenshot looks ok:
<img width="948" alt="screen shot 2017-08-28 at 10 45 39 am" src="https://user-images.githubusercontent.com/540757/29766140-11859cd8-8bde-11e7-802a-7d4441013e30.png">

**Comment by soulgalore** [comment]
It works fine on Linux, so it's a Mac issue, let me have a look later today.

**Comment by pmeenan** [comment]
I just pushed a change that gets the display DPR from the browser on OSX and uses that to scale the crop rectangle.  Tried it out on native and 2x and looks to be working: https://github.com/WPO-Foundation/wptagent/commit/86652c21c5362f8b6f42ef4a80cfc8b52b640971

Should be fixed now.  Re-open if it isn't.

**Comment by soulgalore** [comment]
perfect thanks!
