### ISSUE TITLE
Pass blocked URLs to the --blocked-url-patterns Lighthouse option

### ISSUE THREAD

**Issue by wildlyinaccurate** [WPO-Foundation/wptagent#360]
While it won't be possible to support every script command for the Lighthouse run, there are some like `block` and `blockDomains` that should be relatively easy to implement.

I'm happy to submit a PR for this, but wanted to raise an issue before I did any work in case anyone wants to weigh in.

**Comment by pmeenan** [comment]
Sounds good to me. I already do something similar for non-Chrome browsers where I go through the script and extract the blocked domains commands and just block them all before the test starts (for those that can't do it dynamically).

**Comment by wildlyinaccurate** [comment]
Whoops, I just realised `block` has already been linked up to `--blocked-url-patterns`, and `blockDomains` works on Linux agents by modifying /etc/hosts.
