### ISSUE TITLE
Private WPT - Capture Speed Index in Agent Server without logging into the machine

### ISSUE THREAD

**Issue by shrutiseth** [WPO-Foundation/wptagent#361]
I am able to get Speed Index when submitting a test from Main server to Agent Node only when I login to Agent Server and make sure the Chrome window is in focus. If the Chrome is not in focus, Speed Index is not captured (basically video is not captured).

I plan to schedule WPT tests at particular time of the day/night on Agent Nodes. Is it possible to get Speed Index without actually logging to Agent Server machine?
Could you please help me understand how this can be done?

Thanks!

**Comment by pmeenan** [comment]
The only way is with Linux agents which run headless. You can potentially do it (sort of) with Windows if you set up the agent machine to create a RDP session to itself (different account) at startup. That way the machine itself can stay logged out but the RDP session is logged-in.

The only other option is to use VM's on the machines and keep the main windows session logged out but the VM's running in the background, each logged-in.

Linux agents are by far the easiest (and most reliable) way though.

**Comment by shrutiseth** [comment]
Thanks for suggesting this. Could you please suggest me any article I can refer to for setting this up?

**Comment by pmeenan** [comment]
https://github.com/WPO-Foundation/wptagent/blob/master/docs/install.md#windows

**Comment by shrutiseth** [comment]
Thanks!
