### ISSUE TITLE
Extra requests to laptop-updates.brave.com when testing using Brave

### ISSUE THREAD

**Issue by tvereecke** [WPO-Foundation/wptagent#362]
A WPT test using Brave browser shows 3 additional requests in the critical path. 

The 3 requests to **laptop-updates.brave.com** are not part of the tested page itself.

<img width="744" alt="wpt-extrarequests" src="https://user-images.githubusercontent.com/58261095/87155866-04e55500-c2bc-11ea-87a4-2515303e3658.png">

WPT settings: Default
- From: Ireland - EC2
- Browser: Brave
- Network Cable

The 3 requests are:
- https://laptop-updates.brave.com/promo/custom-headers
- https://laptop-updates.brave.com/promo/initialize/nonua 
- https://laptop-updates.brave.com/1/usage/brave-core?platform=linux-bc&channel=release&version=1.10.97&daily=true&weekly=true&monthly=true&first=true&woi=2020-07-06&ref=BRV00

Note: On repeated tests this was not visible

Kind regards
Tim

**Comment by pmeenan** [comment]
Should be fixed now.  It'll take up to an hour to roll out to the public agents.
