### ISSUE TITLE
CPU throttling doesn't appear to work in desktop tests

### ISSUE THREAD

**Issue by wildlyinaccurate** [WPO-Foundation/wptagent#372]
Comparing these tests:

- [throttle_cpu=8, **mobile=0**](http://wpt1.speedcurve.com/results.php?test=200802_74_5A5P)
- [throttle_cpu=8, **mobile=1**](http://wpt1.speedcurve.com/results.php?test=200802_5D_5A6J)
- [throttle_cpu=0, mobile=0](http://wpt1.speedcurve.com/results.php?test=200802_8S_59YN)

It seems like CPU throttling only works on the mobile test. I can see that ChromeDesktop sets `--disable-features=site-per-process` with a comment saying that site isolation _"breaks CPU throttling on Windows"_. Do you think we should disable site isolation for any test with CPU throttling?

**Comment by pmeenan** [comment]
At one point in time, site isolation broke netlog which is why it was disabled but I think that has long-since been fixed.  I'll take a look tomorrow and if it is working then it makes sense to remove it universally so Chrome is being tested like it normally runs.

**Comment by wildlyinaccurate** [comment]
Did some quick testing on my local agent. Definitely seems like CPU throttling only works when the site-per-process feature is disabled.
