### ISSUE TITLE
wptagent gets stuck issuing an adb command on Android 10 

### ISSUE THREAD

**Issue by muhamd-abdullah** [WPO-Foundation/wptagent#376]
wptagent gets stuck while issuing commands to force close search box in Android 10. ADB becomes dead and the mobile device goes offline and has to be reconnected.

**Comment by pmeenan** [comment]
Can you upload the debug output so I can see exactly which command sequence?  What device (there are a few Android 10 devices running on the public instance without the same issue)?

Should be easy enough to gat the code and not run that part of the cleanup.

**Comment by muhamd-abdullah** [comment]
Thank @pmeenan . It was the "**adb shell pm clear com.google.android.googlequicksearchbox**" command executed by wptagent that caused the ADB to go unresponsive and wptagent to get stuck. I commented the following line in the **adb.py** and the issue got resolved:
`self.shell(['pm', 'clear', 'com.google.android.googlequicksearchbox'])`
 
I was using a private instance and my own Nokia 1 device (running Android 10)
