### ISSUE TITLE
I am getting 0 for Start Render and Speed Index, it's not calculating recently

### ISSUE THREAD

**Issue by ankitjain082** [WPO-Foundation/wptagent#384]
Hi @pmeenan,

I have private instance set up and found that getting 0 for Start Render and Speed Index since today's morning.
Also recorded video is blank(only show black screen).
It's was working fine till yesterday but getting wrong value from today, i saw you did some changes recently so could you verify it again.

I have attached screen shot for the same.

Thanks,
Ankit Jain
<img width="969" alt="Screenshot 2020-10-13 at 1 07 42 PM" src="https://user-images.githubusercontent.com/25079032/95845560-f51c5780-0d67-11eb-8ca5-75b35a290c27.png">
<img width="1422" alt="Screenshot 2020-10-13 at 2 48 54 PM" src="https://user-images.githubusercontent.com/25079032/95845567-f8afde80-0d67-11eb-99d2-457c2dbe3f4f.png">

**Comment by pmeenan** [comment]
Can you reproduce it on the public instance? If so that will make it a lot
easier to debug. If not, and it is easily reproduced in your instance can
you run a test with debug=1 and send the debug log (pmeenan@webpagetest.org
if you want the details private).

All of the testing I've been doing was working but there may be some
combination of options I'm missing that broke.

**Comment by ankitjain082** [comment]
Thanks for the reply. 

I ran on public instances and it's working fine over there, issue is on private instance only.
I'll run it again with debug=1 and share the log with you

Thanks,
Ankit Jain

**Comment by pmeenan** [comment]
It might be a Linux vs windows thing if your agents are windows (most of
the public ones are Linux). I did some windows testing on the thinkpads but
the windows AMIs run an older windows.

**Comment by pmeenan** [comment]
I tried with a Windows AMI and also couldn't reproduce it so I'll probably need the debug log to make any progress on it.

**Comment by pmeenan** [comment]
That should be all that is needed and then the log will be available as a download link to the left of the waterfall like here: https://www.webpagetest.org/result/201013_DiTxY9_5b723da36d4626abcad64a535bcba23e/

**Comment by ankitjain082** [comment]
@pmeenan Thanks for your help, I am closing this issue as it has been resolved.
