### ISSUE TITLE
connecting to socket issue

### ISSUE THREAD

**Issue by gitjpuser** [WPO-Foundation/wptagent#39]
websocket connection issue. Not able to connect websocket.

In my web application first browser make a socket connection then all http requests sending across this websocket. But when i run my application through WPT browser its not creating a socket connection.

**Comment by gitjpuser** [comment]
SCRIPT12002: WebSocket Error: Network Error 12002, The operation timed out

**Comment by gitjpuser** [comment]
Its working fine in chrome and firefox but not working in IE11. Need to add something specific for IE11 browser.

**Comment by pmeenan** [comment]
IE 11 isn't supported.  The only Microsoft browser on Windows currently supported is Edge: https://github.com/WPO-Foundation/wptagent#windows

**Comment by gitjpuser** [comment]
oks, is there any enterprise edition of the same or similar kind of utility, which supports IE11.

**Comment by pmeenan** [comment]
The windoows-only agent supports IE 9-11, Edge, Chrome and Firefox: https://sites.google.com/a/webpagetest.org/docs/private-instances#TOC-Test-Machine-s-1

**Comment by gitjpuser** [comment]
The windows-only agent supports IE 9-11, Edge, Chrome and Firefox: https://sites.google.com/a/webpagetest.org/docs/private-instances#TOC-Test-Machine-s-1

i am using the same one and facing the above mentioned issue. Please help me on the same.

**Comment by pmeenan** [comment]
It's not possible that you are having the above issue with wptdriver.  wptdriver doesn't connect to the dev tools interface or log messages even remotely like that.

**Comment by gitjpuser** [comment]
how to use windows -only agent and can we use as a private instance ?

**Comment by pmeenan** [comment]
The sites link in the page directly above explains how to configure wptdriver for a private instance.  The binary is part of the [webpagetest release](https://github.com/WPO-Foundation/webpagetest/releases).

**Comment by gitjpuser** [comment]
yes i have installed the above same mentioned version..issue is webpage working fine in chrome but not in IE11 version. In web page we have multiple websockets calls (i.e. primus websocket). While debuging we opened the f12 dev tool in the agent intiated IE browser and go to console and refresh the web page then found some websocket connection issues. Please let us know how can we proceed further in that.

**Comment by pmeenan** [comment]
Open an issue in the webpagetest project with the details (as much as possible).  If the site tested is public than an URL and reproducible failcase will help.
