### ISSUE TITLE
Lighthouse scores failing to return a score

### ISSUE THREAD

**Issue by Nooshu** [WPO-Foundation/wptagent#393]
I've tested on a MotoG4 as well as Chrome DT:

## Chrome Desktop ([Test](https://www.webpagetest.org/lighthouse.php?test=210115_DiPG_fbe3bfb8642e7bda5e29b7400952d706&run=2))
> /usr/lib/node_modules/lighthouse/lighthouse-core/gather/driver.js:68
  _traceCategories = Driver.traceCategories;
                   ^

> SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/lib/node_modules/lighthouse/lighthouse-core/runner.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

## MotoG4 1 ([Test](https://www.webpagetest.org/lighthouse.php?test=210115_DiTP_eb99a32421d0f7363d28c5c959922902&run=8))

> lighthouse "https://gds.blog.gov.uk/2020/06/02/what-happened-on-global-accessibility-awareness-day-at-gds/" --channel wpt --enable-error-reporting --max-wait-for-load 80000 --port 9223 --output html --output json --output-path "/home/pmeenan/wptagent/work/MotoG4_01/210115_DiTP_eb99a32421d0f7363d28c5c959922902.1.0/lighthouse.json" --throttling-method provided --save-assets --skip-audits screenshot-thumbnails --form-factor none --screenEmulation.disabled --form-factor desktop --screenEmulation.disabled
Invalid value: 'screenEmulation.disabled' must be a boolean

## MotoG4 2 ([Test](https://www.webpagetest.org/lighthouse.php?test=210115_DiVW_a524eb1e1e8fa5e96eb792d033918b7f&run=3))
> Invalid values:
  Argument: form-factor, Given: "none", Choices: "mobile", "desktop"

**Comment by pmeenan** [comment]
For desktop, I think there is an issue specific to the Atlantic.net London location where lighthouse is corrupt.

```
21:48:05.644 - Error getting lighthouse version
Traceback (most recent call last):
  File "/home/ubuntu/wptagent/internal/devtools_browser.py", line 626, in run_lighthouse_test
    out = subprocess.check_output('lighthouse --version', shell=True, universal_newlines=True)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'lighthouse --version' returned non-zero exit status 1
21:48:05.647 - lighthouse "https://gds.blog.gov.uk/2020/06/02/what-happened-on-global-accessibility-awareness-day-at-gds/" --channel wpt --enable-error-reporting --max-wait-for-load 80000 --port 9249 --output html --output json --output-path "/home/ubuntu/wptagent/work/London/210116_DiM6_89ee6d8f0bd82f2d41c698dea5838117.1.0/lighthouse.json" --throttling-method provided --save-assets --skip-audits screenshot-thumbnails --chrome-flags="--user-agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML like Gecko) Chrome/87.0.4280.141 Safari/537.36 
```

I'll see if I have remote access to repair it but testing from other desktop locations (including [London EC2](https://www.webpagetest.org/result/210116_DiD9_1ba8f9d3805e15418751bd2d6259b6d3/)) seems to be ok.

Looking into the G4's now.

**Comment by pmeenan** [comment]
G4's should be [fixed now](https://www.webpagetest.org/result/210116_DiJ4_3e08360c05c6367c06e337123bd78206/).  Thanks for the report and details, helped track it down quickly.

**Comment by pmeenan** [comment]
Looks like Lighthouse 7 changed the minimum node version to 12 (was 10) and the Atlantic agents were still running node 10.  wptagent has logic to auto-update node so I bumped the minimum node version to 12 and all of the Atlantic locations are working again.  [Here](https://www.webpagetest.org/result/210116_Di02_3023655d8a7f02d5fff37411d4326263/) is the London desktop test re-run.

**Comment by Nooshu** [comment]
Verifies the MotoG4's are now fixed. 

![Screenshot 2021-01-16 at 22 39 43](https://user-images.githubusercontent.com/1223960/104824676-c7a1e700-584b-11eb-87ae-d8e1ceb03560.png)

Thanks Pat 👍
