### ISSUE TITLE
DevTools connection error

### ISSUE THREAD

**Issue by yoavweiss** [WPO-Foundation/wptagent#4]
When trying to run a test with the wptagent on linux, I'm getting devtools connection errors:
`Connect to dev tools Error: HTTPConnectionPool(host='localhost', port=9222): Max retries exceeded with url: /json (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe0a80da0d0>: Failed to establish a new connection: [Errno 111] Connection refused',))`

These errors repeat themselves and the run never completes.

Pointers on how to further debug this would be appreciated :)

**Comment by yoavweiss** [comment]
Oops, looks like a `--xvfb` option missing on a headless machine. so maybe the solution here is to turn on xvfb by default, or a better error?

**Comment by pmeenan** [comment]
Probably worthwhile to add detection at startup to see if the server appears to be headless and have it turn on xvfb automatically if it appears to be (not sure if that is detectable from python but should be possible).

I didn't want to force it universally to allow for testing on systems with real GPU's though that's probably not going to be a common case for people running the Linux agent.

**Comment by mybolide** [comment]
hello, I also encountered this problem now, but I didn't understand how to solve it. I used ubuntu16.04. What should I do?
