### ISSUE TITLE
Running Chrome in data saver mode adds a popup to the filmstrip 

### ISSUE THREAD

**Issue by Nooshu** [WPO-Foundation/wptagent#403]
Enabling data saver mode includes a pop-up overlay at the bottom of the filmstrip, likely throwing out certain metrics.

![filmstrip(2)](https://user-images.githubusercontent.com/1223960/109089758-aaddb680-7709-11eb-80f4-ef312166b079.png)

Test run can be [seen here](https://www.webpagetest.org/video/compare.php?tests=210225_DiDD_51735bfd74e42a0feedd295e7b1b0934-r:7-c:0)

**Comment by pmeenan** [comment]
Hmm.  That seemed to work on desktop but it's still showing on Android.  Back to poking around.

**Comment by pmeenan** [comment]
Oh, maybe it [did work](https://www.webpagetest.org/video/compare.php?tests=210225_DiZ7_8afad0dcb29c5fce21efc1df8fc5ff44-r:1-c:0) after all and I just had to wait for the agents to update.

![Screen Shot 2021-02-25 at 5 21 28 PM](https://user-images.githubusercontent.com/444165/109227187-ed48d700-778d-11eb-9974-412948e0a017.png)
