### ISSUE TITLE
Introducing packet loss improves performance

### ISSUE THREAD

**Issue by Nooshu** [WPO-Foundation/wptagent#407]
## Tests
Setup: Dulles, VA - Moto G4 - Chrome - 450/230 Kbps, 400ms Latency
[Test here](https://www.webpagetest.org/result/210325_Xi9T_08985dbc08c2edacc59b9859c6c6e1e1/6/details/#waterfall_view_step1)

Setup: Dulles, VA - Moto G4 - Chrome - 450/230 Kbps, 400ms Latency, 1% Packet Loss
[Test here](https://www.webpagetest.org/result/210325_XiCc5E_ca13199d55c11375dc31c4961b7500f4/1/details/#waterfall_view_step1)

## Issue
First byte drops from 7.6 seconds to 2 seconds when 1% PL is introduced. This could even be that the no PL scenario is taking way too long.

**Comment by pmeenan** [comment]
Looks like it was just luck of the draw on which test was the median.  [Plotting both tests](https://www.webpagetest.org/graph_page_data.php?tests=210325_Xi9T_08985dbc08c2edacc59b9859c6c6e1e1,210325_XiCc5E_ca13199d55c11375dc31c4961b7500f4-l:loss&medianMetric=SpeedIndex#TTFB) the TTFB varies from 2 seconds (expected) to  8+ seconds. (and the 2 second ones match desktop emulation and are what I'd expect)

Going to have to collect some tcpdumps to see what's going on but I wouldn't be surprised if there was some other background network traffic interfering and maybe there needs to be some logic to wait for the network to go idle before starting.

**Comment by pmeenan** [comment]
Looks like a bunch of QUIC traffic so likely Chrome downloading something.  Going to see if I can figure out what it is and disable it but also add some logic to wait for the network to go idle before starting the test.

**Comment by pmeenan** [comment]
OK, think that nailed it.  Consistency is [much better](https://www.webpagetest.org/graph_page_data.php?tests=210326_XiNA_dbcf284ab3add652d5a5aee50ead34e7&medianMetric=SpeedIndex#TTFB)

Still no idea what it is downloading but my dev device would download 7-10MB of data when the browser started - yikes!

While I was in there, I also added a bandwidth utilization for any devices that are reverse-tethered (all the android devices).
