### ISSUE TITLE
Map shows wrong location name

### ISSUE THREAD

**Issue by d19dotca** [WPO-Foundation/wptagent#409]
When accessing www.webpagetest.org and clicking/tapping on "Select from Map" button, if map around into the California state map pins, one of them (green pin in screenshot below) at the top of the state lists itself as the Toronto location, which is of course incorrect.

![image](https://user-images.githubusercontent.com/8153796/113638040-d027e380-962a-11eb-99fb-3c35b8ece296.png)

Any idea why this is? I notice there's also no pin near the actual location of Toronto either. Almost as if that pin has been moved to the California region. This needs to be corrected.

**Comment by pmeenan** [comment]
Thanks, should be fixed now.  Looks like Paris also had the incorrect lat/lng settings.
