### ISSUE TITLE
Getting error "net::ERR_INSUFFICIENT_RESOURCES" for Chrome only on private instances.

### ISSUE THREAD

**Issue by ankitjain082** [WPO-Foundation/wptagent#417]
Hi,

I have created private WPT server and nodes using docker to run tests but getting a error "net::ERR_INSUFFICIENT_RESOURCES" for chrome only, it's working fine for Firefox.

1 Use below command for server ::

sudo docker run -d -p 4000:80 -v path of file/locations.ini:/var/www/html/settings/locations.ini --restart=always webpagetest/server

2 Use below command for Node ::

sudo docker run -d -p 4001:80 --name wptagent -e "SERVER_URL=http://wpiserverIP:4000/work/" -e "LOCATION=which we mentioned in location.ini file" --cap-add=NET_ADMIN --restart=always webpagetest/agent

I have attached screenshots for the error.
Could anyone help me resolve this issue.

Thanks,
Ankit Jain
<img width="1387" alt="WPTErrorForChrome" src="https://user-images.githubusercontent.com/25079032/122367394-06160c00-cf7a-11eb-848d-704c07e497a4.png">

**Comment by Ankit-TWC** [comment]
Hi,

I got the solution, it's required increase share memory so need to use "--shm-size=2gb" in docker command of Agent.

Thanks.

**Comment by tkadlec** [comment]
Solution looks like it was found. https://forums.webpagetest.org/t/getting-error-net-err-insufficient-resources-for-chrome-only-on-private-instances/11764/2
