### ISSUE TITLE
Login users on Wikipedia on Firefox picks up the the login URL in second step

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/wptagent#43]
Hey Pat,
we use a script like this to login the user:
```
// The login page
logData 0
navigate https://en.wikipedia.org/w/index.php?title=Special:UserLogin&returnto=Main+Page

// Log in the user
setValue        name=wpName     <%WPT_USER>
setValue        name=wpPassword <%WPT_USER_PASSWORD>
submitForm      name=userlogin

// Erase the current HTML to make the video easier to understand
exec document.body.innerHTML = "";
sleep	1

// This is the URL that we want to measure as a logged in user
logData 1
navigate https://en.wikipedia.org/wiki/Facebook
```
And on Linux/Firefox the login URL gets picked up in the waterfall:

http://wpt.wmftest.org/result/170904_0B_9H/1/details/#waterfall_view_step1:

<img width="997" alt="screen shot 2017-09-04 at 11 40 33 am" src="https://user-images.githubusercontent.com/540757/30021300-39248e64-9167-11e7-89ae-f658d66a18bb.png">

On Firefox on Windows the old agent it looks ok:
<img width="961" alt="screen shot 2017-09-04 at 11 41 31 am" src="https://user-images.githubusercontent.com/540757/30021303-3ddc7386-9167-11e7-9ccf-2e2cec1283f8.png">

Best
Peter

**Comment by pmeenan** [comment]
This looks like the same issue as #44.  Could you re-test and see if it is still happening?

**Comment by soulgalore** [comment]
Yep it was the same, just wanted to make sure. Thanks for the fix!
