### ISSUE TITLE
SSL Negotiation times are no longer reported for Firefox

### ISSUE THREAD

**Issue by tkadlec** [WPO-Foundation/wptagent#460]
Looks like Firefox tests no longer report SSL negotiation times. :(
![no-ssl-ff](https://user-images.githubusercontent.com/66536/149217133-55975056-4391-44a3-b1d7-897e7a065ed1.png)

**Comment by tkadlec** [comment]
After digging, this looks like it's due to this change: https://phabricator.services.mozilla.com/D123824

Basically, we parse the Moz Logs and used to look for `EnsureNPNComplete` to signal the end of the SSL negotiation (https://github.com/WPO-Foundation/wptagent/blob/619d0e89d5fe642c35244e1f65829c09384326dd/internal/support/firefox_log_parser.py#L288) period, but Firefox moved that logic out to `HandshakeDone`.

Changing our logic to look for `HandShakeDone` does seem to bring back ssl times, but I'm seeing a slight gap so maybe this still isn't the right log to look at?
![ssl-gaps-ff](https://user-images.githubusercontent.com/66536/149217858-fd63f8d9-07ca-470c-9ec0-491ec43d855c.png)

**Comment by tkadlec** [comment]
@ddragana I hear you're the person to chat to about Network logs stuff. Is there something else I should be looking at in the logs here?

**Comment by tkadlec** [comment]
Actually the little gaps, upon closer look, seem like it's just in-between stuff and overhead. So maybe we just need to confirm `HandshakeDone` is the right thing to look at.

**Comment by ddragana** [comment]
`HandshakeDone` is good enough. It may not be called if the TLS handshake fails. Do you need that case as well?

The best would be to add a log line to the `FinishNPNSetup` function. If you would like to have the log line please open a bug.

**Comment by tkadlec** [comment]
To keep things connected, here's the Bugzilla bug for this request: https://bugzilla.mozilla.org/show_bug.cgi?id=1751201
