### ISSUE TITLE
"SyntaxError: await is only valid in async function" issue in current master version

### ISSUE THREAD

**Issue by anfe0690** [WPO-Foundation/wptagent#481]
Hello, I set up a private instance in a virtual machine with the master branch and I saw an error in the agent logs that disabled some Javascript functionality when using `exec`  or `execAndWait`:
```
SyntaxError: await is only valid in async function
```
I had to replace the master branch for the release branch to make it work again. https://github.com/WPO-Foundation/wptagent-install/blob/master/debian.sh#L46

**Comment by tkadlec** [comment]
Thanks! Reverted the commit that caused that for now.
