### ISSUE TITLE
The server and agent have disappeared

### ISSUE THREAD

**Issue by LRF520** [WPO-Foundation/wptagent#558]
The docker has been cleared. The server and agent have disappeared. Will they not be updated in the future?

![20220807_213027](https://user-images.githubusercontent.com/58470642/183293294-1398a5c3-e092-49ed-90c1-b059f7dfbe95.jpg)

**Comment by mikegeyser** [comment]
Hi, we also discovered this yesterday when trying to rebuild our own containers. I'm not sure why it happened, but it's been very disruptive and is a very disappointing turn of events. We've come to rely on webpagetest in our environment (where everything runs inside a kubernetes cluster), and even though they were out of date - we thought using the 'official' container images would be safer than trying to write our own.

**Comment by tkadlec** [comment]
Sorry about the mixup gang!

Agent is back up now and should stay that way. We've still got some work to do for the server bit, but since we're got an issue for that on the server repo, I'll close this one for now.
