### ISSUE TITLE
Browser version of AWS images?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/wptagent#57]
Hi Pat,
seen we are running Chrome 60 on our agent I guess the agents aren't autoupdating the browser right? What do you think is the best way to handle it in the future: Run on a Linux (AWS or whatever) and then upgrade ourself or will that be built in the agent so we can the AWS images?

Best
Peter

**Comment by pmeenan** [comment]
What are you using for the agents?  The EC2 AMI's that I publish should update themselves.  The Linux ones auto-update hourly from apt and the Windows agents update when I push a new release.  I thought I pushed Chrome 61 the first day it released but I can check to make sure I didn't end up downloading 60 instead.

**Comment by pmeenan** [comment]
FWIW, It looks like the EC2 agents on the public instance [picked up 61](https://www.webpagetest.org/result/170918_6W_fa668a2cebc517068ee2fc3d7b221483/1/details/#step1_request1).  Since wptagent kills the actual chrome updater, presumably they picked it up from when I pushed the release.

**Comment by soulgalore** [comment]
Ok, I run the latest on AWS but I created a new one. Could it be then maybe that it runs the one from the AMI and then next hour pickup the new one? I'll test tomorrow. Thanks!

**Comment by pmeenan** [comment]
Windows?  If so, there are no browsers installed on the AMI.  They won't start testing until they have installed the current release that I have hosted.

**Comment by soulgalore** [comment]
Linux. But let me test more today.

**Comment by pmeenan** [comment]
The Linux AMI's run an apt-get update/dist-upgrade at startup and once a day after that.  The script looks like [this one](https://github.com/WPO-Foundation/wptagent/blob/master/docs/gce_walkthrough.md#install-the-software).  That should update them at launch and there is protection in place to wait for apt to become available but it is possible that the update or upgrade step is failing.

I can change the script to loop on each of those operations until they succeed which might help.

**Comment by soulgalore** [comment]
I think it isn't working when you spin up a new instance (I haven't kept it running to update yet): I automatically spin up new instance and in the HAR for that it is running Chrome 60 http://wpt.wmftest.org/result/170919_48_8S/

I think I run the latest batch of AMIs but I can verify that.

**Comment by pmeenan** [comment]
I just spun up an agent and it does look like the apt update/install was failing because of it running in the background.  I am spinning a new version of the AMI's now that loops on the update until it succeeds.  We won't know for sure until 62 though since the new AMI will already be updated.

**Comment by pmeenan** [comment]
Linux AMI's have all been updated (new ID's).  Also updated ec2locations.ini in case you're using the AMI's from there.

Assuming apt returns an error code when it fails, it should keep trying to do the install until it succeeds at boot now.

**Comment by soulgalore** [comment]
Thanks for the quick fix, I'll update first thing tomorrow!
