### ISSUE TITLE
Dockerfile is missing text file for apt-get

### ISSUE THREAD

**Issue by szepeviktor** [WPO-Foundation/wptagent#626]
Used in 
https://github.com/WPO-Foundation/wptagent/blob/eb86253f0e27463a9ccf2268d41f13e370f7a1bc/Dockerfile#L36-L37

Removed in https://github.com/WPO-Foundation/wptagent/commit/ddf07cd0d1085995155acaa5ec8ec59fc2a70a12#diff-d7950080e66392b2f614c57cf5aa78022506848f254715ad8d95952bdb2cc9c1

**Comment by anthonymunene** [comment]
Could this file please be restored @pmeenan?

**Comment by szepeviktor** [comment]
I have just noticed the missing file. I am not a user.
