### ISSUE TITLE
Setup problems with iOS 11 and Raspbian Stretch Lite

### ISSUE THREAD

**Issue by j0weiss** [WPO-Foundation/wptagent#64]
Hi,

I was trying to run the WPT Agent on a Raspberry Pi 3 (Model B V1.2) with Raspbian Stretch Lite (release date: 2017-09-07, kernel version: 4.9) for an iPhone 7 with iOS 11. During the setup I encountered some stumbling blocks.

The source of the problem seem to be `libimobiledevice` and `ios-webkit-debug-proxy`. Recently there were some issues related to iOS 11 in both of the projects. E.g.:
* https://github.com/libimobiledevice/libimobiledevice/issues/510
* https://github.com/google/ios-webkit-debug-proxy/issues/231

Following the hints given in those issues, I compiled the latest version of `libimobiledevice` and `ios-webkit-debug-proxy` directly from the corresponding repositories. 
After replacing the binaries within WPT Agent with the freshly compiled ones, measurements worked fine with an iPhone running iOS 11.

But I'm still not sure about the exact source of the problem. Which Debian version do you use for your Pi and did you encounter similar problems?

**Comment by pmeenan** [comment]
I'm running on Jessie.  The binaries I had included were already built from master so they should have had the lockdown fix already but maybe something with the build doesn't like running on Stretch.

Were you getting the lockdown error message or a different one?  When I get a few cycles I'll update my dev Pi to Stretch and see if I can reproduce the issues (and see if there is a way to have the same binaries work on both).

**Comment by j0weiss** [comment]
I encountered various hiccups during the set-up, but I think everything boils down to the lockdown error message, yes.
I'll have to look into it a bit more, because now after putting everything into an Ansible role and deploying it to the Pi, the agent doesn't connect to the iPhone anymore.

**Comment by j0weiss** [comment]
Closing this, because we used Jessie for now.
