### ISSUE TITLE
Test hangs without 'Preserve original User Agent string' parameter selected on WPT private instance created using docker

### ISSUE THREAD

**Issue by serputko** [WPO-Foundation/wptagent#67]
In case i run test without 'Preserve original User Agent string' parameter, test execution hangs.
There is an unhandled exception in agent log:
> Unhandled exception: coercing to Unicode: need string or buffer, NoneType found
> Traceback (most recent call last):
>   File "/wptagent/wptagent.py", line 74, in run_testing
>     self.task = self.wpt.get_task(self.job)
>   File "/wptagent/internal/webpagetest.py", line 438, in get_task
>     .replace('%VERSION%', self.version)
> TypeError: coercing to Unicode: need string or buffer, NoneType found
> Traceback (most recent call last):
>   File "/wptagent/wptagent.py", line 74, in run_testing
>     self.task = self.wpt.get_task(self.job)
>   File "/wptagent/internal/webpagetest.py", line 438, in get_task
>     .replace('%VERSION%', self.version)
> TypeError: coercing to Unicode: need string or buffer, NoneType found

It seems that wptdriver version is None because git is not used during instalation and you don't handle that:
` # If we are running in a git clone, grab the date of the last
        # commit as the version
        self.version = None
        try:
            directory = os.path.abspath(os.path.dirname(__file__))
            out = subprocess.check_output('git log -1 --format=%cd --date=raw',
                                          shell=True, cwd=directory)
            if out is not None:
                matches = re.search(r'^(\d+)', out)
                if matches:
                    timestamp = int(matches.group(1))
                    git_date = datetime.utcfromtimestamp(timestamp)
                    self.version = git_date.strftime('%y%m%d.%H%m%S')
        except Exception:
            pass`

**Comment by pmeenan** [comment]
Sorry, should be [fixed now](https://github.com/WPO-Foundation/wptagent/commit/5d6c81e052fc1aa44412eefedca86575b474ccc0)
