### ISSUE TITLE
CrossPlattform Agent and WptDriver Agent traffic shaping results are different

### ISSUE THREAD

**Issue by PhilAlbrecht** [WPO-Foundation/wptagent#69]
Hey there,

we are currently updating our agents from win7 and legacy wpt-driver agent to win10 with the cross-plattform agent.

For about a week we have run tests and aggregated some data. When comparing the data we have noticed some differences shown in the figures below.

- the first figure shows the entry page and the second figure the followup page
- blue is win10+crossplattform agent with traffic shaped to DSL6000 and light blue is win10+crossplattform agent with traffic shaped to HSDPA
- red is win7+wptdriver agent with traffic shaped to DSL6000and orange is win7+wptdriver agent with traffic shaped to HSDPA

![entry_page_recolor](https://user-images.githubusercontent.com/30042849/33657740-80fe025e-da7a-11e7-8f18-2cc707410c6f.png)

![followup_page_recolor](https://user-images.githubusercontent.com/30042849/33657744-83decb7a-da7a-11e7-897c-f0812d2bfd4c.png)

# Connection info
- HSDPA | 3600kbs Download bandwidth | 1500kbs Upload | latency 40ms
- DSL6000 | 6000kbs Download bandwidth | 6000kbs Upload bandwidth | latency 50ms
- hardware of the desktop computers is the same

As seen in the figures, there is quite an offset between the two agent-types with HSDPA Connection. Do you have noticed a similar difference between the results of the two agent-types? or do you maybe have an idea how the difference might have been created?

**Comment by pmeenan** [comment]
There are a few different moving parts.  On Windows 8.1 and later both wptdriver and wptagent use [winshaper](https://github.com/WPO-Foundation/win-shaper) for traffic-shaping and on Windows 7 wptdriver uses dummynet.

There is also the OS difference in case it is an issues of running out of resources.

Can you try running wptdriver on the Windows 10 configuration to see how it performs?  That will at least narrow it down to how the agent automates the browser or winshaper+win10.

One option to help with the migration if shaping or OS cause issues would be to add support for shaping with dummynet on Windows 7 for wptagent.  Shouldn't take more than a couple hours of work.

**Comment by PhilAlbrecht** [comment]
Hey, sorry for the late response - 
I have rerun the test on the same windows10 pc with the new agent (crossplattform) and the old one (wptdriver). It was tested with firefox and 3600kbs download, 1500kbs upload and 40ms latency
Here is the result:
![comparison](https://user-images.githubusercontent.com/30042849/34209928-54bf268a-e594-11e7-87b6-af3c11da3154.png)
I am a bit confused why the results differ that much since they are on the same computer - here are two waterfalls that further highlight the difference:

- example waterfall for page 2 | Old agent (wptdriver)

![waterfall1](https://user-images.githubusercontent.com/30042849/34220931-974c4d4e-e5b6-11e7-94f4-425021b4c544.png)

- example waterfall for page 2 | New agent (crossplattform)

![waterfall2](https://user-images.githubusercontent.com/30042849/34220933-98e215bc-e5b6-11e7-8834-e8d6ee90c1c2.png)

I am just curious as to whether you might have an idea whats the cause for this. Or am I missing something/doing something wrong.

**Comment by PhilAlbrecht** [comment]
Hey there again,

we conducted some further test but the offset between the two agents seems to be still existend, it seems the slower and worse the connection the bigger the offset. However for our usecase we are fine as it is, and sadly we lack the time to conduct further investigation.

Greetings
