### ISSUE TITLE
TTFB for Firefox seems too high?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/wptagent#78]
Hi Pat, 
finally we got the Linux version running side by side with the (old) Windows version. It seems like the TTFB for Firefox is extremely high? We run on Cable and on Chrome we have TTFB like 100-200 ms and that is in the area for our Windows machine. This is Chrome on Linux:
<img width="615" alt="screen shot 2018-02-04 at 7 21 09 pm" src="https://user-images.githubusercontent.com/540757/35780766-98508a0e-09e0-11e8-877a-1539d1dc9fab.png">

But for Firefox TTFB jumps between 350 ms to 1500 ms (we have the same pattern independent on what page we test using Firefox). On Windows we have it constant in the same area as Chrome. This is on Firefox on Linux (same page, same connectivity):
<img width="603" alt="screen shot 2018-02-04 at 7 22 06 pm" src="https://user-images.githubusercontent.com/540757/35780780-c64575aa-09e0-11e8-8bc2-51279fbd8319.png">

Is the TTFB from the MOZ log so something is broken inside of Firefox or how is it calculated?
Best
Peter

**Comment by pmeenan** [comment]
Sounds like an issue with the moz log processing.  Can you shoot me a sample URL and I'll see if I can reproduce it and grab a log.  It may take a little bit since I'm traveling this week for smashing conf.

**Comment by soulgalore** [comment]
Cool, no problem of course. Thanks!

Here's an example run:
http://wpt.wmftest.org/result/180204_HG_XX/ 
for https://en.wikipedia.org/wiki/Facebook

Best
Peter

**Comment by pmeenan** [comment]
Hmm, that doesn't look like a logs processing error (that would have shown up as a large gap before dns).  That looks a lot like issues I would see intermittently when an agent had ipv6 enabled but didn't really have ipv6 networking.  I'll see if the EC2 agents have the ipv6 stack disabled and if nt, disable it and spin some new AMI's to see if that helps.

**Comment by pmeenan** [comment]
I rolled out some new Linux AMI's with IPv6 disabled.  It looks good in the quick tests I ran.  For the public instance I've only moved the Virginia EC2 agents over (just limited time tonight, I'll move the rest over in the morning).

**Comment by soulgalore** [comment]
Thanks, I've just updated to the new AMI, will report back when I get some metrics.

**Comment by soulgalore** [comment]
Yep that fixed the problem, thanks!

**Comment by pmeenan** [comment]
Thanks.  I just finished moving all of the public EC2 agents to the new AMI.  Hopefully not too many more rough edges to sort out.
