### ISSUE TITLE
SetCookie Not working for IE11 Browser

### ISSUE THREAD

**Issue by aravindhan87** [WPO-Foundation/wptagent#81]
I am trying to set a Cookie for IE11 browser through script. But its not taking any of the headers.
 
1.       Tried with add Header: https://www.webpagetest.org/result/180216_KV_2d3c23335bfece598e36648cc37c00b1/1/details/

addHeader         Cookie: DP-Cloud-Origin=cloud1
navigate               https://www.jcpenney.com

2.  Tried with Set Cookie: https://www.webpagetest.org/result/180216_00_96f301999f6342488ea820fc676657f9/1/details/ 

setCookie          https://.jcpenney.com       DP-Cloud-Origin=cloud1
navigate	https://www.jcpenney.com

Both the options didnt work. Can you please help here.

**Comment by aravindhan87** [comment]
Hi Pat!!

Did you got chance to look into the issue.

Thanks

**Comment by pmeenan** [comment]
IE doesn't support setting cookies or modifying headers.  I'll see if webdriver offers anything that will work but if not it is unlikely to get implemented any time soon because it would require a C++ BHO which would be pretty different from how all of the other browsers work.

**Comment by pmeenan** [comment]
Fix for setting cookies in IE is in (will take around an hour to roll out).  Make sure you include the domain though - https://.jcpenny.com won't work.

```
setCookie	https://www.jcpenney.com	DP-Cloud-Origin=cloud1
navigate	https://www.jcpenney.com
```

[Here](https://www.webpagetest.org/result/180313_R2_0845f9acb4b36126c4bcb4cc109119f3/1/details/#step1_request2) is a sample test I ran in the dev environment (also added a cookie bob=uncle just to be sure I wasn't picking up an existing cookie).

**Comment by aravindhan87** [comment]
Its working perfectly.!!!! Thanks :)
