### ISSUE TITLE
Incorrect "result" value when base page is a 404

### ISSUE THREAD

**Issue by wildlyinaccurate** [WPO-Foundation/wptagent#90]
I have a test for [a 404 page](https://www.webpagetest.org/result/180315_DV_7001f8303cca96cdf16defc13c1cf8e2/). I would expect the `result` value of this test to be `404` (based on [this doc](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/result-codes)), but it is `99999`:

```
$ curl -s https://www.webpagetest.org/jsonResult.php\?test\=180315_DV_7001f8303cca96cdf16defc13c1cf8e2 | jq '.data.median.firstView.result'
99999
```

**Comment by pmeenan** [comment]
Thanks.  Looks like Chrome stopped reporting a failed resource load in that case.  I added detection for the main resource returning a failed result code and it is rolling out now.  Should be fully rolled out within the next hour.

[Here](https://www.webpagetest.org/result/180319_A1_9389f86188f42c694121e4a8efe57503/) is what it looks like on my dev instance.

**Comment by wildlyinaccurate** [comment]
Nice! `result` in the JSON looks good to me:

```
$ curl -s https://www.webpagetest.org/jsonResult.php\?test\=180319_A1_9389f86188f42c694121e4a8efe57503 | jq '.data.median.firstView.result'
404
```

Thanks Pat :+1:
