### ISSUE TITLE
htmlbody not supported

### ISSUE THREAD

**Issue by zeman** [WPO-Foundation/wptagent#91]
In the API `htmlbody=1` saves the response body for the base HTML doc and makes it available in the UI. This works as expected using wptdriver but the new wptagent seems to ignore the parameter. Is this intentional or has it not been implemented yet?

**Comment by pmeenan** [comment]
Not implemented yet. I can take a crack at it tomorrow.

________________________________

**Comment by zeman** [comment]
Thanks Pat, not in a massive rush but just wanted to make sure it doesn't get missed. Very useful to have the html to debug without bloating the tests will all the response bodies.
