### ISSUE TITLE
Fully loaded time is too low when using request blocking

### ISSUE THREAD

**Issue by wildlyinaccurate** [WPO-Foundation/wptagent#94]
Hey Pat :grinning: 

I haven't had a chance to play around with this too much so it might just be a coincidence. I'm seeing the fully loaded time being reported as very low whenever I use scripts to block third-party requests. The tests I'll link are for my own website but I'm also able to replicate this on other sites.

 - Just using `navigate` gives a reasonable fully loaded time - https://www.webpagetest.org/result/180328_7Y_a22af79766101fe1ae72fe459f68cc36/1/details/
 - When using `blockDomainsExcept`, fully loaded happens before start render - https://www.webpagetest.org/result/180328_X1_0c016c10497ce5dedfebd018b784cec5/5/details/
 - Same with using plain ol' `block` - https://www.webpagetest.org/result/180328_CJ_5917a8ee3200132345165857e2eebbf0/1/details/
 - But it seems ok in Firefox - https://www.webpagetest.org/result/180328_T7_41a6d1312d2d8c23ba15313a20ec5c4f/1/details/

I wanted to see if I could help debug this further, but I got stuck at the first hurdle: I can see that the other desktop browsers calculate the fully loaded time in `calculate_page_stats` but Chrome does not. Is this because Chrome exposes the page stats in some internal API and `calculate_page_stats` is just a shim for the other browsers?

**Comment by pmeenan** [comment]
Chrome should do it in the devtools_parser.py logic where it parses the raw dev tools events, merges the netlog timings and calculates the page-level stats.  That makes it easier to debug as well because you can take the raw results from a test and run it through the parser stand-alone as often as you need and not have to keep re-running tests.

I'll take a look and see if anything jumps out.

**Comment by pmeenan** [comment]
Fix just pushed.  It was calculating the fully loaded time just off of the dev tools timings before the timings were fixed up from the netlog.  The fix is to recalculate it after all of the timing fixup is done.
