### ISSUE TITLE
Testing with a real android device

### ISSUE THREAD

**Issue by soulcorrosion** [WPO-Foundation/wptagent#97]
I'm trying to setup a simple example running the docker image of the agent on windows. I was interested in trying to connect an android device but I'm a bit lost and with not much expertise on the subject.

I was looking for a step by step guide in accomplish such task. I found this documentation from a former node.js agent (https://sites.google.com/a/webpagetest.org/docs/private-instances/node-js-agent/setup), but it's deprecated. I guess it does not apply anymore but it should be simpler to setup with the new wptagent

Can anyone help?

**Comment by pmeenan** [comment]
This might help: https://github.com/WPO-Foundation/webpagetest-docs/blob/master/user/Private%20Instances/mobile/example.md

________________________________
