### ISSUE TITLE
How often do releases get tagged in Docker?

### ISSUE THREAD

**Issue by soulgalore** [WPO-Foundation/wptagent#98]
Hi Pat,
giving another go at using the Docker and checking https://hub.docker.com/r/webpagetest/agent/tags/
it seems only one release (with a specific tag has been released). Is the plan to release a real release each month or?

The reason is that I need unique tags to be able to lock to a specific version, and then every X week/month update the container to the latest released version.

Best
Peter

**Comment by pmeenan** [comment]
Plan was to do named releases every 3 months. I'm running a bit behind on the latest but I'll cut it when I get back in town next week.

________________________________

**Comment by soulgalore** [comment]
Perfect thanks!

Just to be 100% safe: If I set the agentUpdate to an empty string on my server, the Docker agent will never update automatically. But if it is set, it will update?

Also is there a conceptual difference between the _release_ and _latest_ tag in the Docker repo?

**Comment by pmeenan** [comment]
Just comment out or remove the agentUpdate entry in settings.ini if you don't want the old wptdriver agent to auto-update.  It doesn't do anything with the wptagent agents or server code though.  The server auto-updates from git based on the git update entry (forget the actual key) and it updates from the release branch which is more stable than trunk but quite a bit more often than the named releases.

"release" in Docker tracks the release branch (updated weekly or so when there are relevant changes).  "latest" tracks the master and is updated quite a bit more frequently.

**Comment by soulgalore** [comment]
Any change we can get a named release soon again? Every 3 months is perfectly ok for us. It's just if we move to run the Docker version instead, it makes our workflow easier and more controlled.

**Comment by soulgalore** [comment]
Perfect, thanks!
